### ISSUE TITLE
Header is overlapping page content on the 2nd page and beyond

### ISSUE THREAD

**Issue by szTheory** [pdfkit/pdfkit#113]
I've got a header and footer. On my content's body tag, I've applied a padding-top so the content is pushed down below the header on my first page. However on the 2nd page and beyond, content is being overlapped by the header.

Is there any way to "hook" into page breaks that are automatically generated, for example if a DOM element is created, that way I can apply a CSS padding-top to it and push down my content on subsequent pages?

**Comment by kamaroly** [comment]
@sigmavirus24 ,
would you be so kind to post the solution here?

**Comment by sigmavirus24** [comment]
@kamaroly I don't have the solution. Sorry.
