### ISSUE TITLE
Errno::EPIPE (Broken pipe):

### ISSUE THREAD

**Issue by gasova** [pdfkit/pdfkit#121]
Before anything, I followed all steps but without success.

I googled and found similar problems  but no working solution. Same issue with wicked_pdf 

I'm on Linux CentOS  5 with Rails 3.0.10 and Apache 2 with Phusion Passenger 

wkhtmltopdf is setup and works perfectly on the linux prompt. 
I'm able to generate a pdf with wkhtmltopdf http://www.google.com google.pdf without any issue.

When I try to generate a PDF I have the error : Errno::EPIPE (Broken pipe):
the html renders well but pdf fails.

Can somebody help me please? 

My Full log : 

tarted GET "/posts/cesur-bir-hasmin-ardindan.pdf" for 85.105.12.197 at 2011-12-11 17:36:57 +0200
  Processing by PostsController#show as HTML
  Parameters: {"id"=>"cesur-bir-hasmin-ardindan"}
  Post Load (2.0ms)  SELECT `posts`.\* FROM `posts` WHERE `posts`.`cached_slug` = 'cesur-bir-hasmin-ardindan' LIMIT 1
  Dashboard Load (0.2ms)  SELECT `dashboards`.\* FROM `dashboards`
  Post Load (0.3ms)  SELECT `posts`.\* FROM `posts` WHERE `posts`.`id` = 248
  Author Load (0.3ms)  SELECT `authors`.\* FROM `authors` INNER JOIN `authorships` ON `authors`.id = `authorships`.author_id WHERE ((`authorships`.post_id = 248)) LIMIT 1
  Column Load (0.2ms)  SELECT `columns`.\* FROM `columns` WHERE `columns`.`id` = 16
  CACHE (0.0ms)  SELECT `posts`.\* FROM `posts` WHERE `posts`.`id` = 248
  CACHE (0.0ms)  SELECT `authors`.\* FROM `authors` INNER JOIN `authorships` ON `authors`.id = `authorships`.author_id WHERE ((`authorships`.post_id = 248)) LIMIT 1
  Post Load (6.2ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 30)) ORDER BY published_at DESC LIMIT 3
  CACHE (0.0ms)  SELECT `posts`.\* FROM `posts` WHERE `posts`.`id` = 248
  CACHE (0.0ms)  SELECT `authors`.\* FROM `authors` INNER JOIN `authorships` ON `authors`.id = `authorships`.author_id WHERE ((`authorships`.post_id = 248)) LIMIT 1
  SQL (0.4ms)  SELECT COUNT(_) FROM `comments` WHERE `comments`.`post_id` = 248 AND `comments`.`status` = 1
  CACHE (0.0ms)  SELECT `dashboards`._ FROM `dashboards`
  CACHE (0.0ms)  SELECT `dashboards`.\* FROM `dashboards`
  Banner Load (0.2ms)  SELECT `banners`.\* FROM `banners` ORDER BY id ASC
  Author Load (0.5ms)  SELECT `authors`.\* FROM `authors` WHERE (id > 1) ORDER BY name ASC
  Post Load (1.3ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 46)) ORDER BY published_at DESC LIMIT 1
  Post Load (2.1ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 45)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.3ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 53)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.7ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 44)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.4ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 43)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.7ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 20)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.3ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 52)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.1ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 41)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.1ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 10)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.5ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 39)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.1ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 35)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.3ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 34)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.3ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 42)) ORDER BY published_at DESC LIMIT 1
  Post Load (6.0ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 30)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.6ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 54)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.7ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 33)) ORDER BY published_at DESC LIMIT 1
  Post Load (2.5ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 36)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.5ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 38)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.1ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 32)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.3ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 55)) ORDER BY published_at DESC LIMIT 1
  Post Load (1.0ms)  SELECT `posts`.\* FROM `posts` INNER JOIN `authorships` ON `posts`.id = `authorships`.post_id WHERE ((`authorships`.author_id = 37)) ORDER BY published_at DESC LIMIT 1
  SQL (0.3ms)  SELECT COUNT(_) FROM `authors` WHERE (id > 1)
  Category Load (0.2ms)  SELECT `categories`._ FROM `categories`
Rendered posts/show.html.erb within layouts/public (125.8ms)
Completed 200 OK in 130ms (Views: 82.6ms | ActiveRecord: 53.2ms)

Errno::EPIPE (Broken pipe):

**Comment by mikecmpbll** [comment]
Just in case it helps anyone else, I appear to have got this error using the "viewport_size" config option in an older version of wkhtmltopdf—I upgraded wkhtmltopdf to fix.
