### ISSUE TITLE
new version of wkhtmltpdf (0.10.2)

### ISSUE THREAD

**Issue by prikha** [pdfkit/pdfkit#139]
Hi guys! *PDFKit* is a great way to deal with generating pdf reports, however it has been a while since wkhtmltopdf moved ahead to version 0.10.2 - it is the lowest version i can compile from source with latest webkit. 

Unfortunatelly wkhtmltopdf changed the way arguments are passed into it. For example cover in now passed like this 
`wkhtmltopdf cover 'http://google.com'` and not like it was before `wkhtmltopdf -cover 'http://google.com'`  therefore rails fails to generate pdf with cover option mentioned. 

Could you please guide me through!!! What can i do to make it work, or maybe there is a patch or separate branch?

**Comment by cdwort** [comment]
@prikha I'm sorry this issue sat so long without a response. I believe #296 fixed this issue and those changes will go out in version 0.7.1.

In the meantime, the changes are on the master branch if you would like to use that.
