### ISSUE TITLE
Setting Margins

### ISSUE THREAD

**Issue by Melonbwead** [pdfkit/pdfkit#149]
Are there anyway of setting the PDFkit's Margin tobe none? It's scaling my page pdf to a smaller size at the moment.

Thanks.

**Comment by leighmcculloch** [comment]
You can also do the following which keeps your style outside of your code. It's ashame PDF Kit / wkhtmltopdf don't pick this up from the CSS on the `body` element – now that'd be sweet.
```html
<meta name="pdfkit-pag_size" content="Letter"/>
<meta name="pdfkit-margin_top" content="0.25in"/>
<meta name="pdfkit-margin_right" content="0.25in"/>
<meta name="pdfkit-margin_bottom" content="0.25in"/>
<meta name="pdfkit-margin_left" content="0.25in"/>
```

**Comment by PatrickatPaperlessPCS** [comment]
@leighmcculloch just stumbled across your solution - where are you putting this code?  I've been trying every way possible to address in CSS!

**Comment by leighmcculloch** [comment]
@PatrickatPaperlessPCS you want to put this code into the `<head>` of your html template that you give to `PDFKit`. Take a look at [spiffy](https://github.com/leighmcculloch/spiffy) which uses PDFKit and it's templates set the margins – checkout these files:
* [template](https://github.com/leighmcculloch/spiffy/blob/master/templates/default.haml) – put the pdfkit options into the `<head>`, this template uses haml which I'm convering to html, but just imagine it's plain html.
* [spiffy.rb](https://github.com/leighmcculloch/spiffy/blob/master/lib/spiffy.rb) – `PDFKit.new(html)` with the `html` template.

**Comment by PatrickatPaperlessPCS** [comment]
Ah @leighmcculloch I see - I copied and pasted your suggestion above and ran into an error.  Thought I'd misplaced it but `<meta name="pdfkit-pag_size" content="Letter"/>` should be `<meta name="pdfkit-page_size" content="Letter"/>` (left off the e in page).  Works well, thanks for the tip!

**Comment by dimanyc** [comment]
@leighmcculloch OMG. I've been tearing my hair out trying to figure out why my PDF looks different in production: http://stackoverflow.com/questions/43151028/rendered-pdf-looks-different-in-production-rails-pdfkit-wkhtmltopdf. Is there a way to see all available options that can be appended as metas?

**Comment by leighmcculloch** [comment]
@dimanyc: I'm not sure, but from browsing the source in this repo it looks like the pdfkit gem strips the `pdfkit-` meta prefix and then passes the name verbatim to the `wkhtmltopdf` command. So I'd take a look at `wkhtmltopdf` and see what options it supports.

**Comment by imtiaz-emu** [comment]
> You can also do the following which keeps your style outside of your code. It's ashame PDF Kit / wkhtmltopdf don't pick this up from the CSS on the `body` element – now that'd be sweet.
> 
> ```
> <meta name="pdfkit-pag_size" content="Letter"/>
> <meta name="pdfkit-margin_top" content="0.25in"/>
> <meta name="pdfkit-margin_right" content="0.25in"/>
> <meta name="pdfkit-margin_bottom" content="0.25in"/>
> <meta name="pdfkit-margin_left" content="0.25in"/>
> ```

Literal copy pasting will lead you to an error. `<meta name="pdfkit-pag_size" content="Letter"/>` should be changed to `<meta name="pdfkit-page_size" content="Letter"/>` to make it work.

**Comment by blueridger** [comment]
Syntax seems to have changed slightly. This worked for me (dashes instead of underscores).
```
<meta name="pdfkit-page-size" content="Letter"/>
<meta name="pdfkit-margin-top" content="0.25in"/>
<meta name="pdfkit-margin-right" content="0.25in"/>
<meta name="pdfkit-margin-bottom" content="0.25in"/>
<meta name="pdfkit-margin-left" content="0.25in"/>
```
I also needed to make sure to use a version of wkhtmltopdf with "patched qt" so run `wkhtmltopdf --version` and make sure it outputs something that ends in `(with patched qt)`
