### ISSUE TITLE
wkhtmltopdf hangs?

### ISSUE THREAD

**Issue by netwire88** [pdfkit/pdfkit#157]
I installed PDFKIt and wkhtmltopdf on Mac. When I try to generate PDF from webpage, wkhtmltopdf seems to hang. I see this message:

```
The switch --print-media-type, is not support using unpatched qt, and will be ignored.
```
My `application.rb` file containts `config.middleware.use "PDFKit::Middleware", :print_media_type => true`

and I have another `pdfkit_asset.rb` file per http://jguimont.com/post/2627758108/pdfkit-and-its-middleware-on-heroku
```
ActionController::Base.asset_host = Proc.new { |source, request|
  if request.env["REQUEST_PATH"].include? ".pdf"
    "file://#{Rails.root.join('public')}"
  else
    "#{request.protocol}#{request.host_with_port}"
  end
}
```

**Comment by cdwort** [comment]
Closing as this is unrelated to PDFKit. Thanks all for the information.
