### ISSUE TITLE
URLs being escaped after upgrade to 0.5.3

### ISSUE THREAD

**Issue by KidkArolis** [pdfkit/pdfkit#166]
Our PDF generation broke after update to 0.5.3

The URL we're opening is something like

```
PDFKit.new("http://localhost/?some_param=1", {})
```

In 0.5.3, that URL is converted to something like (I checked in the server's access log):

```
http://localhost/\?some_param=1
```

and the request fails.

**Comment by cdwort** [comment]
I believe this is related to #164, which lead to this commit: https://github.com/pdfkit/pdfkit/commit/ce37ffcdb223b34dd215971e2cd365e3a66cb5f1

We are now using `shelljoin` instead of `shellescape`, but I imagine the issue may still remain.
