### ISSUE TITLE
pdfkit should be explicit about the error when all margin units are not the same

### ISSUE THREAD

**Issue by henrik** [pdfkit/pdfkit#174]
wkhtmltopdf requires all margin units to be the same, e.g.:

```
$ wkhtmltopdf --margin-left 30mm --margin-right 1in test.html out.pdf
Loading page (1/2)
Error: Currently all margin units must be the same!
```

But if I pass the same options to pdfkit, I get a generic "command failed: …" message that never mentions the units.

**Comment by mb21** [comment]
as of `wkhtmltopdf 0.12.6`, the error is still very confusing, e.g passing only `--margin-left 30mm` gives:

    Error: Currently all margin units must be the same!  

I'd suggest a better error message would be:

    Error: Currently all margin units must be the same! Note that the default unit is inch.

Thus if you want to set only one margin, you need to set it in inces, e.g. `--margin-left 3in`
