### ISSUE TITLE
wkhtmltopdf: cannot connect to X server

### ISSUE THREAD

**Issue by daniel2d2art** [pdfkit/pdfkit#180]
Hi here 
This is working Ok from console Centos 6.x:

``` bash
wkhtmltopdf --print-media-type --use-xserver --quiet www.google.com ~/google.pdf
```

But when working from pdfkit v0.5.3 gem in RoR v3.2.1

```
RuntimeError (command failed: "/usr/local/bin/wkhtmltopdf" "--print-media-type" "--use-xserver" "--quiet" "-" "-"
```

And Apache error:

```
wkhtmltopdf: cannot connect to X server
```

We're using Xvfb as Xserver

**Comment by timothymarois** [comment]
I'm sorry that this is an incredibly old thread, but I've been trying to overcome the same error. On Red Hat (64-bit). `wkhtmltopdf: cannot connect to X server` No matter what I do. Ive installed via the steps above and have installed via sudo yum, both success. But when running the `wkhtmltopdf` command, it shoots out that error message.

**Comment by timothymarois** [comment]
I think I've figured it out need to have `xorg-x11-server-Xvfb` installed for Redhat. I'll continue to see if everything else functions as normal.

**Comment by alexburcea2877** [comment]
wget http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-static-amd64.tar.bz2
--2017-12-06 19:23:04--  http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-static-amd64.tar.bz2
Resolving wkhtmltopdf.googlecode.com (wkhtmltopdf.googlecode.com)... 2607:f8b0:400e:c00::52, 173.194.202.82
Connecting to wkhtmltopdf.googlecode.com (wkhtmltopdf.googlecode.com)|2607:f8b0:400e:c00::52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-06 19:23:04 ERROR 404: Not Found.
