### ISSUE TITLE
utf8 handling issue

### ISSUE THREAD

**Issue by jystewart** [pdfkit/pdfkit#21]
I'm working on an application that's entirely utf8 based and uses a wide range of non-ascii characters. 

When using wkhtmltopdf on the command line my pages are cleanly converted to PDF with the characters render appropriately, but when I request them through my rails app/pdfkit the characters are being mangled (eg. "Tröhler" is becoming "TrÃ¶hler")

I'm using Ruby Enterprise Edition 1.8.7 (2010.02 - can't switch to 1.9 yet), I've checked the locale on my system and it's set to en_GB.UTF8. Is there anything else I should be exploring?

**Comment by jessamynsmith** [comment]
In case this helps anyone else, I was having an issue, even with the doctype and html. What helped was changing my code to this:

```
import codecs
import pdfkit

input_filename = 'input.html'
output_filename = 'output.pdf'

with codecs.open(input_filename, "r", "utf-8") as f:
    html_text = f.read()
    pdfkit.from_string(html_text, output_filename)
```

**Comment by sigmavirus24** [comment]
@jessamynsmith this is the Ruby pdfkit project :)

**Comment by jessamynsmith** [comment]
Oops. Well, the doctype and html stuff still helped me. :)

**Comment by sigmavirus24** [comment]
No worries @jessamynsmith :)
