### ISSUE TITLE
UTF-8 characters using --footer-left or --footer-right does not render properly

### ISSUE THREAD

**Issue by jgrau** [pdfkit/pdfkit#223]
Hi

Inserting text with UTF-8 chars into the footer using the `--footer-left` or `--footer-right` option does not seem to produce the correct result. See attached image. Code:

```
# Initializer
PDFKit.configure do |config|
  config.default_options = {
   :encoding => "UTF-8"
  }
end

# Controller
options = {
    :footer_left => "Special Char Test ÆØÅ"
}
kit = PDFKit.new("Testing special chars in body: ÆØÅ", options)
```

Ruby: 1.8.7
OS: OSX Mavericks.
wkhtmltopdf: 0.9.9
pdfkit: 0.5.4

All help is greatly appreciated.

![screenshot 2014-02-10 00 32 20](https://f.cloud.github.com/assets/108088/2121371/72f8004a-91e2-11e3-87ae-114de7675fc8.png)

**Comment by allaire** [comment]
That fixed it for me too with the upstart script, thanks!
