### ISSUE TITLE
Error on include header after update to 0.6.1

### ISSUE THREAD

**Issue by gbonline** [pdfkit/pdfkit#227]
Hi, I used Pdfkit for my project, where pdf docs have header and footer, and I used the syntax
%meta{:name => 'pdfkit-header_html', :content => pdf_header_url}
on my haml pdf_layout.rb file.

Then I updated my gems and with the new 0.6.1 version i've got the following error

No route matches [GET] "/pdf/header'%20name='pdfkit-header_html"

but all gone well before update with the 0.5.4 version. 
On routes.rb I have the path pdf/header and it's accessible from browser.
Giorgio

**Comment by Priya5** [comment]
I am using pdfkit (0.6.2) and  wkhtmltopdf-binary-edge (0.12.2.1) and i have added header using
 %meta{:name => 'pdfkit-header_html', :content => url }
I had successfully generated pdf with small number of pages but once i tried for pdf with more than 100 pages, the report generation command failed with

QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe

RuntimeError: command failed (exitstatus=): '/.rvm/gems/ruby-2.1.2/bin/wkhtmltopdf' '--page-size' 'Letter' '--margin-top' '1.3in' '--margin-right' '0.5in' '--margin-bottom' '0.75in' '--margin-left' '0.5in' '--quiet' '--header-html' [header_path] '--footer-html' [footer_path] '--header-spacing' '7.7' '--footer-spacing' '7' '-' '/var/folders/9d/g1hm6l755rb2m86nrz9fp1200000gq/T/d20150507-5292-1hi9a58/report.pdf'
.rvm/gems/ruby-2.1.2/gems/pdfkit-0.6.2/lib/pdfkit/pdfkit.rb:73:in `to_pdf'
.rvm/gems/ruby-2.1.2/gems/pdfkit-0.6.2/lib/pdfkit/pdfkit.rb:78:in `to_file'

But, the report generation worked fine for any number of pages when i don't have any header_html.

**Comment by cdwort** [comment]
@Priya5 Sorry for the delay in responding. In the future, it can be helpful if you open a new issue.

This looks to me like a problem with wkHTMLtoPDF. PDFKit is a thin wrapper around that command-line utility, and, for your command, we don't open any files besides the destination file and any stylesheets you may have passed in.

**Comment by cdwort** [comment]
@Higorhicaro the header-html is a wkHTMLtoPDF option. It is language agnostic, so it must be supplied HTML, not an erb file. It will also likely need a full path to the header you need.

**Comment by cdwort** [comment]
This issue seems to contain references to three separate problems, although everyone is using the header_html option. I am closing this issue - please open a new issue if you continue to see problems and we can continue to address your problem.
