### ISSUE TITLE
After update from 0.5.4 to 0.6.1 rendering pdf fails

### ISSUE THREAD

**Issue by dovadi** [pdfkit/pdfkit#228]
I get the following error:

<pre>
RuntimeError: command failed (exitstatus=0): wkhtmltopdf --encoding UTF-8 --page-size A4 --orientation Portrait\'\ name\=\'pdfkit-orientation --margin-bottom 0mm\'\ name\=\'pdfkit-margin-bottom --margin-top 15mm\'\ name\=\'pdfkit-margin-top --margin-left 5mm\'\ name\=\'pdfkit-margin-left --margin-right
</pre>

in

<pre>
/gems/pdfkit-0.6.1/lib/pdfkit/pdfkit.rb:73 in "to_pdf"
</pre>

After a rollback to 0.5.4 the problem disappears.

Any clues?

**Comment by PatrickatPaperlessPCS** [comment]
Running into a similar issue in 0.6.2, only on Heroku with error:  `RuntimeError (command failed (exitstatus=0): /app/vendor/bundle/ruby/2.1.0/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --print-media-type - -):`  Works and unable to reproduce on local machine, only breaks on Heroku

**Comment by alvarezloaiciga** [comment]
:+1:

**Comment by sigmavirus24** [comment]
@alvarezloaiciga could you explain your comment?

@PatrickatPaperlessPCS I seem to have missed your comment. Did you figure out what problem you're experiencing?

**Comment by alvarezloaiciga** [comment]
it was actually a +1,  `gem wkhtmltopdf-binary` was not working but I was able to fix it locally installing [wkhtmltopdf OSX package](http://wkhtmltopdf.org/downloads.html). And referencing it from the initializer like: `config.wkhtmltopdf = '/usr/local/bin/wkhtmltopdf'`.

**Comment by sigmavirus24** [comment]
@alvarezloaiciga sorry, I'm failing to see how this relates to this issue.
