### ISSUE TITLE
Print as landscape with middleware

### ISSUE THREAD

**Issue by sobrinho** [pdfkit/pdfkit#23]
Hello,

I'm using PDFKit on my rails application and I need to set the pdf as landscape but I'm using the middleware.

Is this possible?

I tried this css but doesn't work (maybe wkhtmltopdf issue?):

<pre><code>@page {
  size: landscape; }</code></pre>

**Comment by ncaves** [comment]
> Sure, just use the 'orientation' option for wkhtmltopdf.
> 
> # when setting up middleware
> config.middleware.use PDFKit::Middleware, :orientation => 'Landscape'
> 
> # or as a meta tag in the HTML

<meta name="pdfkit-orientation" content="Landscape"/>

**Comment by ncaves** [comment]
<meta name="pdfkit-orientation" content="Landscape"/>
