### ISSUE TITLE
Broken Pipe Error recently

### ISSUE THREAD

**Issue by solars** [pdfkit/pdfkit#232]
Hi there,

Not sure if this is the right place to ask. I've upgraded an application that uses wkhtmltopdf to generate PDFs.
Suddenly I get a lot of Broken Pipe errors:

https://gist.github.com/solars/c6216951acbbb982d8d9

Can anyone tell me what can cause this? The errors seem irregular

**Comment by MhdSyrwan** [comment]
A note that maybe helpful her: This happens when you install `wkhtmltopdf` via the `wkhtmltopdf-binary` gem

**Comment by cdwort** [comment]
Thank you @MhdSyrwan for posting what you found. I am going to close this issue.

**Comment by lacostenycoder** [comment]
I'm having this issue now.
![screen shot 2016-02-24 at 1 21 35 pm](https://cloud.githubusercontent.com/assets/6077905/13296132/f10a2a0a-daf9-11e5-839d-58c7546d54e3.jpg)

**Comment by yattias** [comment]
Me too
