### ISSUE TITLE
upgrading to wkhtmltopdf 0.12.0 results in exitstatus 1 on middleware

### ISSUE THREAD

**Issue by omarqureshi** [pdfkit/pdfkit#234]
I was having trouble getting all my Javascript loaded in time so upgraded to wkhtmltopdf 0.12.0

Generation through the use of `kit = PDFKit.new(url); kit.to_file(location)` works as expected. However the middleware comes up with

`RuntimeError (command failed (exitstatus=1): /usr/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -):`

I'll try and set up a dummy Rails app to replicate this behaviour.

**Comment by pkpp1233** [comment]
+1

**Comment by LFoos24** [comment]
+1

**Comment by fenec** [comment]
I have this error on Mac OS 10.9

**Comment by EminenceHC** [comment]
Same here. PDF generation works from console, but not from inside my rails controller when trying to create PDF:

kit = PDFKit.new('http://localhost:3000/intake_agreements/1')
kit.to_file('public/PDF/kit.pdf')

http://localhost:3000/intake_agreements/1 is SUPER barebones, no relative stylesheets/javascript with the most bare bones custom layout.

If I change command to PDFKit.new('http://www.google.com')  it will save to a PDF just fine. It seems to just have trouble from localhost. I have tried solutions from just about every post on PDFkit.

wkhtmltopdf 0.12.2.1
Ruby 2.0.0p594
Rails 4.0.2

Always hangs on:
Loading pages (1/6)
[======>                                                     ] 10%

When I stop the server I recieve error:

command failed (exitstatus=1): /Users/travis.glover/.rvm/gems/ruby-2.0.0-p594/gems/wkhtmltopdf-binary-edge-0.12.2.1/bin/wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 http://localhost:3000/intake_agreements/1 public/PDF/kit.pdf

**Comment by pranav7** [comment]
+1

**Comment by cdwort** [comment]
@pranav7 What version of PDFKit are you using?

**Comment by sigmavirus24** [comment]
@cdwort I think @pranav7 was saying they tested PDFKit with an unknown version of wkhtmltopdf and was going to send a patch helping us with the upgrade. Right @pranav7?

**Comment by pranav7** [comment]
@cdwort @sigmavirus24 Sorry about this. The problem was [Sing Thread Issue](https://github.com/pdfkit/pdfkit#troubleshooting), ironically the first point for troubleshooting. :\
