### ISSUE TITLE
Homebrew: "no available formula for wkhtmltopdf"

### ISSUE THREAD

**Issue by daveliepmann** [pdfkit/pdfkit#235]
Contrary to [the installation instructions for Mac](https://github.com/pdfkit/pdfkit/wiki/Installing-WKHTMLTOPDF), homebrew installation fails:

> $ brew update
> Already up-to-date.
> $ brew install wkhtmltopdf
> Error: No available formula for wkhtmltopdf
> Searching taps...
> $

**Comment by devmike01** [comment]
This is still a problem. Can someone please help on this?

**Comment by serene** [comment]
@devmike01 Use the wkhtmltopdf install instructions here: https://wkhtmltopdf.org/downloads.html
