### ISSUE TITLE
footer_html expects URL

### ISSUE THREAD

**Issue by reiz** [pdfkit/pdfkit#238]
I'm using Pdfkit in a rake task to generate some invoices. It was very easy to get started. Great project! 

For the footer I'm using this code: 

```
footer_file = "app/views/settings/payments/receipt_footer.html"
kit = PDFKit.new(html, :footer_html => footer_file, :page_size => 'A4')
```

That works fine on localhost and on the CI system. But on production I get this error message: 

```
Error: Failed loading page http://app/views/settings/payments/receipt_footer.html?page=1&section=Receipt - VersionEye&subsection=&frompage=1&subsubsection=&topage=1&webpage=foobar&time=8:51 PM&date=6/5/14 (sometimes it will work just to ignore this error with --ignore-load-errors)
QPaintDevice: Cannot destroy paint device that is being painted
```

Why is pdfkit using the `http://` prefix on production? I can not reproduce it on localhost. For me it looks like a bug. Can I force it somehow that it does the lookup on the file system, instead of http? I appreciate any input. Thx.

**Comment by nearapogee** [comment]
Just an FYI for anyone that stumbles upon this ticket. wkhtmltopdf requires .html file extensions... Ruby Tempfile tack a random string after the file extension (or whatever you put in as the basename), which makes wkhtmltopdf puke.

Hope that helps save someone some time!
