### ISSUE TITLE
Start testing on AppVeyor

### ISSUE THREAD

**Issue by sigmavirus24** [pdfkit/pdfkit#247]
I'm using this to track efforts to start testing pdfkit on a Windows continuous integration system.

Ideally, this would help prevent issues like #183 from happening again.

**Comment by cdwort** [comment]
The sticking point here was getting wkhtmltopdf to install on Windows, correct?

**Comment by sigmavirus24** [comment]
@cdwort correct. Specifically on AppVeyor using powershell and all the other weirdness that was happening.
