### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by mrsimo** [pdfkit/pdfkit#26]
I'm getting things like "CaptaciÃ3n" on the PDF when I should be getting "Captación". It's ok if I escape everything buy it's a little painful when the website works in perfect utf-8. Any hint on this?

**Comment by oshanz** [comment]
is this fixed? because I'm getting error when trying to save a file.
ex:
```ruby
kit = PDFKit.new('http://google.com')
IO.write("test.pdf", kit.to_pdf)

    Encoding::UndefinedConversionError: "\xFE" from ASCII-8BIT to UTF-8
```

**Comment by serene** [comment]
@oshanz What operating system are you running this on? This is quite an old ticket, so I'm guessing it has since been fixed.

**Comment by oshanz** [comment]
@serene ubuntu 18:04. Everything is latest.
