### ISSUE TITLE
Spurious extra line in source?

### ISSUE THREAD

**Issue by JacobEvelyn** [pdfkit/pdfkit#263]
Glancing at the source code, it looks like this line is a mistake? https://github.com/pdfkit/pdfkit/blob/master/lib/pdfkit/pdfkit.rb#L70

Fortunately, it looks like it doesn't impact behavior:

```
raise "1" if
raise "2" if false or false
=> nil

raise "1" if
raise "2" if false or true
=> RuntimeError: 2

raise "1" if
raise "2" if true or false
=> RuntimeError: 2

raise "1" if
raise "2" if true or true
=> RuntimeError: 2
```

**Comment by cdwort** [comment]
Hi @JacobEvelyn,

Thanks for opening the issue! Yeah, that line is extraneous. It looks like it was added while updating our error handling, and the author chose to go with the solution just below that line.

I've removed it in #294. Thanks again.

Have a great weekend :sun_with_face:

**Comment by JacobEvelyn** [comment]
Just making sure I'm not crazy, thanks! :)
