### ISSUE TITLE
QSslSocket: cannot resolve SSLv2_client_method

### ISSUE THREAD

**Issue by pkpp1233** [pdfkit/pdfkit#272]
I'm running a ruby script with pdfkit and keep getting this error at the end of it:

QSslSocket: cannot resolve SSLv2_client_method

I can't figure out how to get rid of it. Or is there any way to silence?

**Comment by sigmavirus24** [comment]
So this doesn't come from pdfkit. It probably comes from `wkhtmltopdf`. That said, it sounds like you have a version of openssl that's compiled without the symbols for SSLv2 and SSLv3. You should follow up on this upstream at wkhtmltopdf.

**Comment by pkpp1233** [comment]
Right. But is there a way to pass configs to wkhtmltopdf? Like --quiet tag?

**Comment by sigmavirus24** [comment]
I'm not sure that will work since `--quiet` is passed by default.
