### ISSUE TITLE
Limit routes with Sinatra?

### ISSUE THREAD

**Issue by Eising** [pdfkit/pdfkit#273]
The documentation states that you can limit routes using `config.middleware.use` syntax, which I can see is for rails. Now I need to serve a few static pdf files with sinatra, but am unable to get the Except syntax working with Sinatra. My config.ru says:

````
use PDFKit::Middleware, :page_size => 'A4', :print_media_type => true, :footer_center => "[page]/[toPage]", :footer_font_size => 10, :except => [%r[^/public]]
````

This doesn't work. How should I do it?

**Comment by cdwort** [comment]
Hello @Eising 

Sorry for the delay. The except option in middleware is supposed to work with any Rack application, so I'm more suspicious of how we apply the regex. 

This is how we exclude routes (with `can_access` added for clarity):

```
@request = Rack::Request.new(env)

def can_access
@conditions[:except].each do |pattern|
  return false if @request.path =~ pattern
end
```

Is there anyway, for the routes you're trying to exclude, that you can access what the `@request.path` is and whether your regex would match?

**Comment by cdwort** [comment]
Closing due to lack of response.
