### ISSUE TITLE
command failed (exitstatus=1)

### ISSUE THREAD

**Issue by suratpyari** [pdfkit/pdfkit#274]
I am getting following error

RuntimeError (command failed (exitstatus=1): /var/www/apps/sophyapp-staging/shared/bundle/ruby/2.1.0/bin/wkhtmltopdf --quiet --page-size letter --margin-top 0.01in --margin-right 0.01in --margin-bottom 0.01in --margin-left 0.01in --encoding UTF-8 --header-spacing 0 - -):

I am using pdfkit-0.6.2.

**Comment by sigmavirus24** [comment]
You can configure pdfkit to not use `--quiet` so you can get more details as described in the documentation. This is not a bug. For support questions please use StackOverflow.
