### ISSUE TITLE
Runtime Error with Heroku deployment

### ISSUE THREAD

**Issue by PatrickatPaperlessPCS** [pdfkit/pdfkit#281]
I'm running into an error after pushing my app to heroku:
`RuntimeError (command failed (exitstatus=0): /app/vendor/bundle/ruby/2.1.0/bin/wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --print-media-type - -):`

Initially thought it was a problem with my worker processes, but I haven't been able to track it down to that.  I'm using pdfkit 0.6.2 with unicorn.

**Comment by cdwort** [comment]
Hi @PatrickatPaperlessPCS 

This is a wkhtmltopdf issue. I would guess that it might relate to lack of access to an image/javascript/stylesheet somewhere.

I would try upgrading wkhtmltopdf as they now have somewhat more verbose error messages that you might be able to see in your log if you turn the production log level up to debug.

An example of the logging you can now get:
<img width="1411" alt="screen shot 2015-08-19 at 8 11 27 pm" src="https://cloud.githubusercontent.com/assets/1014482/9373307/971f775a-46ae-11e5-83a6-0d591cd2f25e.png">

If you search for "ContentOperationNotPermittedError", you'll find that it means that one of the image links didn't resolve and caused wkhtmltopdf to bork. I would love it if wkhtmltopdf's error messages were a little more intuitive, but at least they now have something to google.
