### ISSUE TITLE
PDFKit hangs on OS X but works ok on Ubuntu

### ISSUE THREAD

**Issue by WagnerMatos** [pdfkit/pdfkit#283]
I'm having an issue that only occurs on my Mac (Yosemite): When the method is called, the application hangs and nothing happens, however the same code works fine on Ubuntu (12.04). I though it was wkhtmltopdf (0.12.2.1 on the Mac) but when I tried to generate a pdf with the following command: `/usr/local/bin/wkhtmltopdf http://www.google.com google.pdf` the PDF was generated fine. I don't know which version of wkhtmltopdf I've got on the Ubuntu machine (I'm on my way to the office and will update the issue when I get there) but I imagine the issue is with PDFKit. Am I right?

**Comment by serene** [comment]
What server are you using? Does anything appear in the logs?

**Comment by cdwort** [comment]
@WagnerMatos Actually, when we've had hanging issues they have been tracked back to certain wkhtmltopdf versions on certain OSs. Did you ever find the version you were using on Linux?

**Comment by cdwort** [comment]
Closing due to lack of response. Please update this ticket if you can retrieve the information and we can reopen this issue.
