### ISSUE TITLE
Runtime error, tried on 2 machines.

### ISSUE THREAD

**Issue by Vizakenjack** [pdfkit/pdfkit#285]
Hello. I use ruby 2.0.0 p643, I tried wkhtmltopdf 0.12.2.1 and 0.12.2, pdfkit with the master branch.

wkhtmltopdf works in console, and PDFkit works when I use it as

     kit = PDFKit.new("http://www.google.ca")

But when I try to use it as middleware (adding .pdf to url), it doesn't work neither on my OS X development machine, nor on the linux server (ubuntu 14). Same error: 

     RuntimeError (command failed (exitstatus=1): /usr/local/bin/wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --ignore-load-errors - -):
     pdfkit (0.6.2) lib/pdfkit/pdfkit.rb:73:in `to_pdf'
     pdfkit (0.6.2) lib/pdfkit/middleware.rb:22:in `call'

How can I fix it?

**Comment by cdwort** [comment]
@Vizakenjack I would suggest you post this on StackOverflow, pasting in your configuration and usage of PDFKit. Otherwise, if you can post that information here, we can try to debug your application code.

**Comment by sigmavirus24** [comment]
Questions definitely belong on [StackOverflow](http://stackoverflow.com/questions/tagged/pdfkit). If the answer to that question leads to a bug report with details, then that belongs here.
