### ISSUE TITLE
Provide option for streaming the PDF into IO object

### ISSUE THREAD

**Issue by dnagir** [pdfkit/pdfkit#289]
The `PDFKit#to_pdf` is great except that it keeps the copy of the whole document in memory.

It would help if there was `PDFKit#to_io(io_object)`  to allow streaming directly without using a big temporary blob in memory.
This would help a fair bit in Rails apps where we can just manually feed PDF directly into the `response.stream`.

Is this reasonable?

**Comment by sigmavirus24** [comment]
@dnagir just want to clear up a few assumptions I had made when I read this:

- the `io_object` can be assumed to have a `write` method
- this will be roughly equivalent to `io_object.write to_pdf`
- you will expect to get the file object back in a state where you can just do `io_object.read` without having to find the beginning of the PDF.

The last bullet is most important. It means that all `io_objects` must be seek-able, i.e., we have to be able to discern the start point of the object when we received it (`#tell`) and be able to get back to that point.

Cheers,

**Comment by JacobEvelyn** [comment]
Is there any movement on this?

**Comment by eidge** [comment]
We're generating some big reports (sometimes 300+ pages) which are very expensive to keep in memory.

Is there any way I could help with this feature? What's the current status?
