### ISSUE TITLE
brfs dependency

### ISSUE THREAD

**Issue by cybrown** [pdfkit/pdfkit#290]
brfs is a devDependency, but it seems to be needed even in production.

Do I use this lib the wrong way, or should brfs be in the production dependencies ?

**Comment by sigmavirus24** [comment]
Are you certain this has been filed on the correct project? There is no such dependency in the gemspec or Gemfile.

**Comment by sigmavirus24** [comment]
I suspect you're looking for https://devongovett.github.io/pdfkit/

**Comment by cybrown** [comment]
Yes I'm sorry... have a nice day

**Comment by sigmavirus24** [comment]
You too!
