### ISSUE TITLE
applying the page border style 

### ISSUE THREAD

**Issue by mkosuri** [pdfkit/pdfkit#304]
Pdfkit is Very Good resource for generating pdf . But I did not find the any resource to page border and overide default_options.
i used below code to over ride the default css.
  config.default_options = {
  	:quiet => true,
    :page_size => 'A4',
    :margin_top    => 0,
    :margin_right  => 0,
    :margin_bottom => 0,
    :margin_left   => 0,
    :encoding => 'UTF-8'
  }
And also i want to apply the border style property to the pdf . Can any one suggest me ?
Thanks
madhu

**Comment by sigmavirus24** [comment]
Questions belong on [StackOverflow](https://stackoverflow.com/questions/tagged/pdfkit). This is a defect tracker.

**Comment by mkosuri** [comment]
its my request can please suggest me how to apply border .
