### ISSUE TITLE
Errno::ENOENT: No such file or directory - /tmp/1234_pdf

### ISSUE THREAD

**Issue by Hareramrai** [pdfkit/pdfkit#305]
Hi there, 

I am facing the below error for https urls and using pdfkit (0.7.0).    

````
 kit = PDFKit.new('https://cas-site-manager.herokuapp.com/user_session/new')
 => #<PDFKit:0x0000000260f890 @source=https://cas-site-manager.herokuapp.com/user_session/new, @stylesheets=[], @options={"--quiet"=>nil, "--page-size"=>"Letter", "--margin-top"=>"0.75in", "--margin-right"=>"0.75in", "--margin-bottom"=>"0.75in", "--margin-left"=>"0.75in", "--encoding"=>"UTF-8"}> 
1.9.3p484 :002 > tmp = "/tmp/1234_pdf"
 => "/tmp/1234_pdf" 
1.9.3p484 :003 > kit.to_file tmp
QSslSocket: cannot resolve SSLv2_client_method
QSslSocket: cannot resolve SSLv2_server_method
Error: Failed loading page https://cas-site-manager.herokuapp.com/user_session/new (sometimes it will work just to ignore this error with --ignore-load-errors)
Errno::ENOENT: No such file or directory - /tmp/1234_pdf
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/pdfkit-0.7.0/lib/pdfkit/pdfkit.rb:186:in `size'
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/pdfkit-0.7.0/lib/pdfkit/pdfkit.rb:186:in `empty_result?'
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/pdfkit-0.7.0/lib/pdfkit/pdfkit.rb:71:in `to_pdf'
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/pdfkit-0.7.0/lib/pdfkit/pdfkit.rb:76:in `to_file'
	from (irb):3
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
	from /home/stcadmin/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
````

But Its working for non https urls.  

````
 kit = PDFKit.new('http://cas-site-manager-qa.herokuapp.com/user_session/new')
 => #<PDFKit:0x00000002bb76f8 @source=http://cas-site-manager-qa.herokuapp.com/user_session/new, @stylesheets=[], @options={"--quiet"=>nil, "--page-size"=>"Letter", "--margin-top"=>"0.75in", "--margin-right"=>"0.75in", "--margin-bottom"=>"0.75in", "--margin-left"=>"0.75in", "--encoding"=>"UTF-8"}> 
1.9.3p484 :007 > kit.to_file tmp
 => #<File:/tmp/1234_pdf> 

````

Thanks for your help.

**Comment by sigmavirus24** [comment]
The QSslSocket errors are most likely indicative of the fact that wkhtmltopdf cannot create a secure/verified connection to the server. It would appear that either:

A) wkhtmltopdf only ever tries to use SSLv2 to connect to a server
B) Heroku only serves their app over SSLv2

B) seems far less plausible than A) to me. This seems to be fundamentally a wkhtmltopdf problem. Thoughts @pdfkit/rb?

**Comment by Hareramrai** [comment]
@sigmavirus24 : I am guessing the error might be due to downloading the html content using https url.

**Comment by sigmavirus24** [comment]
@Hareramrai that is a tautological statement. You see the error only when you use `https://` as the protocol. You'll never see any error messages about SSLv2 unless you're attempting to use TLS to talk to a server (which should only happen with `https://`). I'm trying to give you an explanation why. My best guess is that `wkhtmltopdf` is doing the wrong thing here.

We already check for errors so it's unclear to me why this doesn't raise an exception from pdfkit (instead of from the stdlib trying to open the file) unless wkhtmltopdf only reports this problem in stderr and doesn't change it's exit status.

**Comment by Hareramrai** [comment]
@sigmavirus24  I have checked with wkhtmltopdf and its not working. 

thanks for your help ...

**Comment by sigmavirus24** [comment]
You're welcome @Hareramrai
