### ISSUE TITLE
command failed error issue while trying to generate pdf file.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [pdfkit/pdfkit#307]
Hi,I was trying to convert HTML to PDF using pdfkit gem.I configure the path but when tried to generate the pdf file after click on download button first it is taking too much time to load and finaly it is throwing the following error.

command failed: C:/wkhtmltopdf/bin/wkhtmltopdf.exe --encoding UTF-8 --page-size A4 --margin-top 0.25in --margin-right 0.1in --margin-bottom 0.25in --margin-left 0.1in --print-media-type --quiet - -

The following is my pdfkit.tb file

PDFKit.configure do |config|
    #config.wkhtmltopdf =Rails.root.join('bin', 'wkhtmltopdf-i386').to_s
    config.wkhtmltopdf='C:/wkhtmltopdf/bin/wkhtmltopdf.exe'
  config.default_options = {
    :encoding=>"UTF-8",
    :page_size=>"A4",
    :margin_top=>"0.25in",
    :margin_right=>"0.1in",
    :margin_bottom=>"0.25in",
    :margin_left=>"0.1in",
    :disable_smart_shrinking=> false
  }
end

and i am trying to generate the below pdf.

def download_pdf
	   #html = render_to_string(:action => "download_pdf.html.erb")
       #kit = PDFKit.new(html)
       #send_data(kit.to_pdf, :filename => 'report.pdf', :type => 'application/pdf', :disposition => 'inline')
       kit = PDFKit.new("download_pdf.html.erb", :page_size => "A4")
      file = kit.to_file("my_file_name.pdf")

	end
I need to run this in windows 7(32 bit)/xp(64 bit).Please help me to resolve this issue and generate the pdf successfully in windows environment.

**Comment by cdwort** [comment]
Hi @subhrajyotiw5rtc 

PDFKit is a light wrapper around wkHTMLtoPDF, so the first step is to make sure that wkHTMLtoPDF can run happily. In your method definition, can you log or otherwise retrieve `kit.command`? That will output the full command that wkHTMLtoPDF is having trouble with.

When you run that command from the command-line, what output does wkHTMLtoPDF give you?

**Comment by cdwort** [comment]
As with your previous issue, I am closing this issue because we don't have enough information to investigate it. If you are able to provide the information above, please post it here and we'll re-open this issue.

Thank you.
