### ISSUE TITLE
Is there a way to specify start and end page, or page range?

### ISSUE THREAD

**Issue by dbkaplun** [pdfkit/pdfkit#308]

**Comment by cdwort** [comment]
Hi @dbkaplun 

PDFKit is just a wrapper around wkHTMLtoPDF, which has documentation here: http://wkhtmltopdf.org/usage/wkhtmltopdf.txt

It looks like you'll want to use the "--page-offset" option to set a start page. You would set that like this: 
`PDFKit.new('html', page_offset: 5)`

You can also set that option in the configuration file or in each HTML source with meta tags.

After a first glance, I don't see a way to say the last page or to set a range in the wkHTMLtoPDF options, but that's an issue for you to follow up with wkHTMLtoPDF.
