### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by brewster1134** [pdfkit/pdfkit#31]
i have been using PDFKit with middleware for awhile, and it works great, but i wanted to give my invoices a custom file name.  so now i have this...

```
 def to_pdf
   @invoice = Invoice.find(params[:id])
   pdf = PDFKit.new(:html, :title => "Invoice_#{@invoice.id}").to_file(invoice_path)
 end
```

when i hit that controller, i get:
No such file or directory - /en/invoices/1

however if i browse to that url, i see my invoice just fine.  any thoughts?

**Comment by stevenspiel** [comment]
Broken link. Here is an archive of the page https://web.archive.org/web/20120917194205/http://www.jonathanspies.com/posts/11-Simple-PDFkit-example-in-Rails-3
