### ISSUE TITLE
escaped characters in options

### ISSUE THREAD

**Issue by burningTyger** [pdfkit/pdfkit#311]
I'm forwarding usernames and passwords for a basic auth protected app under sinatra. It seems like pdfkit escapes the option values and therefore changes the included password which has escapable characters. I'm not sure what to do now. I can see that escaping is a good thing in the shell but I can't restricts passwords either. Is there any way I can fix this behaviour?

Thank you.

**Comment by cdwort** [comment]
Hi @burningTyger 

Just wanting to clarify - is this a plain text password in the URL? Or is this in some other option?

Can you show me the wkHTMLtoPDF command you would like to run with some example problematic characters?

Thanks

**Comment by burningTyger** [comment]
Hi @cdwort,

This is the line I'm passing on:

    PDFKit::configure do |config|
      config.default_options[:orientation] = 'Landscape';
      config.default_options[:page_size] = 'A3';
      config.default_options[:username] = request.env["REMOTE_USER"];
      config.default_options[:password] = user_pass[:p]
    end

so `user_pass[:p]` just returns the password for my user and forwards it to wkHTMLtoPDF. Going through the pdfkit source code I assume some characters are escaped for shell security reasons. That's what probably causes bogus passwords if they contain characters like `<>`.

I fixed it for now with a different password policy but in general this is not perfect.

Thank you for your help!

**Comment by cdwort** [comment]
@sigmavirus24 If you have a moment, do have thoughts on escaping usernames and passwords? wkhtmltopdf provides this as a feature, so it seems reasonable that we should support it.

Obviously, there are security concerns here, but I'd rather fall on the side of supporting all wkhtmltopdf functionality than saving our users from their own users. Someone could set a password that includes a shell attack. I'm not sure it's our job to protect against that.

Thoughts?

**Comment by sigmavirus24** [comment]
> wkhtmltopdf provides this as a feature, so it seems reasonable that we should support it.

I don't quite agree. PDFKit is mostly used in web applications that are hoping to serve a PDF to their users.

> I'd rather fall on the side of supporting all wkhtmltopdf functionality than saving our users from their own users.

I disagree. I think we should be helping protect our users. We might be able to figure out a smarter way to do this though.

**Comment by sigmavirus24** [comment]
```irb
irb(main):001:0> require 'shellwords'
=> true
irb(main):002:0> ["foo", "bar", "biz>baz"].shelljoin
=> "foo bar biz\\>baz"
irb(main):003:0> foo = _
=> "foo bar biz\\>baz"
irb(main):004:0> foo
=> "foo bar biz\\>baz"
irb(main):007:0> puts `echo '#{foo}'`
foo bar biz\>baz
=> nil
irb(main):008:0> puts `echo #{foo}`
foo bar biz>baz
```

Demonstrated slightly differently, 

```rb
# shellargs.rb
puts ARGV
```

```
~ ruby shellargs.rb foo bar bogus\>baz
foo
bar
bogus>baz
```

As far as wkhtmltopdf should be concerned the >'s shouldn't be problematic.
