### ISSUE TITLE
Single Pdf file from multi html pages

### ISSUE THREAD

**Issue by heartfulbird** [pdfkit/pdfkit#314]
How to do it?

**Comment by cdwort** [comment]
Hello @heartfulbird 

Questions and debugging issues belong on stackoverflow.com. This is are is for tracking bugs in the PDFKit gem.

**Comment by heartfulbird** [comment]
Thank you for your answer!
But can you say it's possible? 
I can't find info about how can I do it with gem pdfkit. 
I can do it only in command line like: 
wkhtmltopdf -O Landscape --dpi 600 01.html 02.html combined.pdf
But we already work with PDFKit gem and I don't know - to continue it or do it with shell commands.

**Comment by cdwort** [comment]
Hi @heartfulbird 

Ah, okay, examples help! 

Unfortunately, we don't currently have support for multiple local files. I think we accidentally support multiple links. That's a combination of oversight in how PDFKit was originally built to be used and the fact that (speaking only for the past couple months I've been here) we don't really see that many advanced uses of wkhtmltopdf's features.

This is a bug. Thanks for bringing it up.

I would refer you to WickedPDF, which has alternate option parsing that ours and can sometime be a quick-ish fix if you don't have too much invested in PDFKit. Unfortunately, they don't seem to support multiple files either. :(

For now, I don't have an answer for you. I can likely get a new feature out quickly for PDFKit's timeframe, but that may not help you - especially if you can't upgrade.

**Comment by heartfulbird** [comment]
Ok, Thank you very much!
It seems this is helpful feature) 
May be in future it will appear.
I will try to work with command line still.
Thank you!

**Comment by serene** [comment]
I would suggest trying to use something like pdftk to merge pdf files.
