### ISSUE TITLE
Use Print CSS

### ISSUE THREAD

**Issue by nasht00** [pdfkit/pdfkit#337]
When looking at Chrome's "print to pdf", the PDF generated by `pdfkit` is very different.
Is this expected?

I suppose that chrome generates a "printer-friendly" version with extra built-in CSS rules.
Is there a way to simulate this behavior?

Also, assume that my own CSS file contains `print` rules as well?

**Comment by sigmavirus24** [comment]
1. We don't accept questions on the issue tracker; use [StackOverflow](https://stackoverflow.com/questions/tagged/pdfkit) instead.

2. PDFKit wraps wkhtmltopdf which handles generating the PDFs from HTML. If you have a feature request or bug about that process, file it with wkhtmltopdf.
