### ISSUE TITLE
Create folder if non-exsistent

### ISSUE THREAD

**Issue by nasht00** [pdfkit/pdfkit#338]
Using `file = kit.to_file("path/to/file")` I get an error in the folders `path/to` don't exist.

Is there a flag I can set somewhere to create the folders if they don't exist? Or some other workaround I can use?

**Comment by sigmavirus24** [comment]
You mean something like

```rb
require 'fileutils'

pdf_directory = 'path/to'
FileUtils.mkdir_p(pdf_directory) unless File.exists?(pdf_directory)
file = kit.to_file("#{pdf_directory}/file")
```
