### ISSUE TITLE
Warning: File has unbalanced q/Q operators (too many q's)

### ISSUE THREAD

**Issue by tomardern** [pdfkit/pdfkit#339]
Hi,

I'm using PDFKit to create a PDF with several pages then print using CUPS. It prints up to the last page, then gives the following message:

D [19/Nov/2015:16:01:47 +0000] [Job 95] Set job-printer-state-message to "Processing page 7...", current level=INFO
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** Warning: File has unbalanced q/Q operators (too many q's)
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** This file had errors that were repaired or ignored.
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** The file was produced by: 
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** >>>> PDFKit <<<<
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** Please notify the author of the software that produced this
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** file that it does not conform to Adobe's published PDF
D [19/Nov/2015:16:01:47 +0000] [Job 95] **** specification.

Any ideas?

**Comment by sigmavirus24** [comment]
So, first:

- Are you sure you're using the ruby project and not the node.js project of the same name?
- I've never seen this before
- We don't ever claim to produce a PDF because the actual PDF generation is done by a different tool which leads me back to my first question.

**Comment by tomardern** [comment]
I'm very sorry - I accidentally entered this onto the wrong tab (I had this and the node.js) repo open.

**Comment by sigmavirus24** [comment]
@tomardern No worries! That's why I asked the question. This is a frequent occurrence.
