### ISSUE TITLE
Expose middleware's #translate_paths, for non-rack usage

### ISSUE THREAD

**Issue by danbernier** [pdfkit/pdfkit#343]
The middleware _basically_ just turns a response's HTML into PDF, and streams it back. But a key part of that process is translating the relative asset paths to absolute URLs, so wkhtmltopdf can include them in the result.

It'd be nice if this functionality was exposed, rather than hidden inside the Rack middleware.

Here's my motivating use-case: I have a rails controller action and view that I render as PDF. Separately, I have a form where a user can request that the PDF is generated, and sent to another user. I'm using `render_to_string` to get the HTML for the PDF, but before I can pass it to PDFKit, I need to translate the paths. It works if I `send(:translate_paths, html, env)`, which is of course not a good idea.

My current thinking is that #translate_paths could be extracted into a separate PDFKit class, and exposed, but I'd love to hear thoughts on other approaches to solving the problem.

**Comment by sigmavirus24** [comment]
> My current thinking is that #translate_paths could be extracted into a separate PDFKit class, and exposed, but I'd love to hear thoughts on other approaches to solving the problem.

So you're thinking about something that might look like

```rb
# lib/pdfkit/translator.rb
class PDFKit
  module PathTranslator
    def translate_paths(body, env)
       # ...
    end

  private

    def translate_relative_paths(body, env)
        # ...
    end

    def translate_relative_protocols(body, env)
       # ..
    end
  end
end
```

Then we could do 

```rb
# lib/pdfkit/middleware.rb
class PDFKit
  class Middleware
    # ...
    def call(env)
      # ...
        body = PDFKit.new(PathTranslator.translate_paths(body, env), @options).to_pdf
      # ...
    end
    # ...
  end
end
```

I'm :+1: on that but I'd like to hear @pdfkit/rb 's opinions too.

**Comment by danbernier** [comment]
That's the gist, yeah.

**Comment by sigmavirus24** [comment]
Cool, just wanted to make sure we were all on the same page.

**Comment by danbernier** [comment]
Another way to think about this is "moving" the `:root_url` middleware configuration option into standard PDFKit. Currently, that option is only read by the middleware when it translates the paths; we could move the path translation, and the reading of the configuration, right into PDFKit core.

The middleware would still have to extract the appropriate root URL from the environment, so it might look something like this:
```ruby
options = @options.merge(root_url: get_root_url_from(env))
body = PDFKit.new(translate_paths(body, env), options).to_pdf
```

My use-case would look about like this:
```ruby
html = render_to_string('other_controller/action')
PDFKit.new(html, root_url: request.host).to_file('to-deliver.pdf')
```
