### ISSUE TITLE
Missing Tag for v0.8.2

### ISSUE THREAD

**Issue by mmichaa** [pdfkit/pdfkit#346]
Hi folks, I'm just missing the git tag for the gem version v0.8.2 that is available on available on rubygems: https://rubygems.org/gems/pdfkit/versions. Thanks!

**Comment by sigmavirus24** [comment]
I think @cdwort has this on their computer.

**Comment by cdwort** [comment]
Yes @mmichaa I should have access to my personal computer later today.

**Comment by cdwort** [comment]
done. Thanks!
