### ISSUE TITLE
Errno::ENOENT No such file or directory when creating PDF to file in 0.8.2

### ISSUE THREAD

**Issue by dhaneberg** [pdfkit/pdfkit#349]
After an upgrade von 0.6.2 to 0.8.2 I encountered an Errno::ENOENT error while trying to create a PDF to file.

The error comes from the empty_result? method and is triggered by File.size(path). And in fact, the file doesn't exist in the directory even though the creation did not report any error.

My guess is that the error was introduced by adding "if path.nil?" in line 68 of pdfkit/pdfkit.rb
After I removed this change, forcing the file to always be read, the error does not appear and the file is created as expected.

**Comment by dhaneberg** [comment]
I have some additional information after doing some more testing. The issue seems to be operating system dependent. I do not get the error on MacOS, but it happens on Ubuntu 14.04.3 LTS. In both cases I used Ruby 2.1.2p95, Rails 4.1.14 and pdfkit 0.8.2

**Comment by albertopriore** [comment]
Hi @dhaneberg 
I'm having the same issue. On MacOS all fine on production server fails.
Did you investigate more on the issue? Or the temporary fix is still to remove the "if path.nil?" check?

**Comment by dhaneberg** [comment]
Hi albertopriore!
Unfortunately removing the check is still the solution of choice, at least for me. My production server works with the patched gem and I have neither the time nor the Ruby knowledge to develop a proper operating system independent fix for the gem.

**Comment by belaustegui** [comment]
I'm also having the same issue. Maybe this workaround could be useful http://stackoverflow.com/questions/15662756/generating-file-with-pdfkit-on-heroku-no-such-file-or-directory

**Comment by caherrerapa** [comment]
@belaustegui did u find any workaround? i'm stuck in the same issue

**Comment by hendricius** [comment]
Did you guys find a solution to this problem?

**Comment by fylooi** [comment]
Had the same problem, narrowed it down to the `wkhtmltopdf-binary` gem binary not working. Reinstalled and it worked fine . Suspect OSX Sierra upgrade broke stuff.

**Comment by stevenspiel** [comment]
Also having this issue. Works fine on MacOS, breaks on Ubuntu servers. pdfkit 0.8.2, Rails 4.2.7.1, Ruby 2.3.1

**Comment by arturtuii** [comment]
I had the same problem but with this solution I managed to solve
http://stackoverflow.com/questions/5035601/error-running-wkhtmltopdf-error-while-loading-shared-libraries

**Comment by smocaine** [comment]
I'm also running into this issue, but removing "if path.nil?" didn't work for me. The linked stackoverflow posts also didn't work. I'm not using the wkhtmltopdf-binary gem. I'm able to render a pdf using to_pdf, but not to_file. I'm on Ubuntu 14.04 with Rails 3.2.12. Has anyone else managed to solve this?

**Comment by patYakk** [comment]
Despite the correction (removing "if path.nil?") , after some while, the issue ENOENT came back.
The reboot of the Linux (Ubuntu 16.04) server got positive  effects, and the issue disappears again.
Very strange..

**Comment by serene** [comment]
Solved in https://github.com/pdfkit/pdfkit/issues/349#issuecomment-300491055

**Comment by zhaowenjun333** [comment]
in window，1.install *.exe 2.add to PATH 3.restart pycharm  4.run perfect ，done.

**Comment by henkjanwils** [comment]
Im my case updating "wkgtmltopdf" to the latest version resolved it!
