### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by abelards** [pdfkit/pdfkit#350]
Hi everyone,
`wkhtmltopdf` says a return code `0` is OK, and `1` is "OK but there's been some problems with URLs".
see -> https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1502

Sometimes that's just good enough and I suggest we make an option to allow these returns and go on.

Not sure where that `success?` is defined though:
https://github.com/pdfkit/pdfkit/blob/6a4b4727fa7eb8bae88652e8cacf12d7ce26751f/lib/pdfkit/pdfkit.rb#L131

If you're OK I may add an option yet to name: laxist? permissive? allow_url_errors? allow_code_1?
so PDFKit's caller may define what is or is not acceptable to them.

What do you think?

**Comment by sigmavirus24** [comment]
Alternate idea: Allow users to configure which status codes they want to believe are "successful" that way we can keep the current behaviour but users can add 1 and whatever else wkhtmltopdf decides to use in the future.
