### ISSUE TITLE
Devnagari characters arent printed correctly.

### ISSUE THREAD

**Issue by kavitakanojiya** [pdfkit/pdfkit#354]
I have added हिंदी in HTML page and then converting to PDF. But pdf generated shows this:
![screen shot 2016-03-17 at 3 14 41 pm](https://cloud.githubusercontent.com/assets/1167590/13842179/dfc7daf2-ec52-11e5-8146-7ad25543e69b.png)

which is wrong. I am stuck on this from long time.

Also, I got Arial Unicode MS installed on my system. Doubting if it has really to do with system fonts.

Please provide some insights. Rest of the foreign characters works just fine. Struggling hard enough to make it work with Hindi/Devnagari characters.

Thanks

**Comment by sigmavirus24** [comment]
This repository only accepts bug reports and feature requests in the issue section. Questions and requests for assistance are best directed to [StackOverflow](https://stackoverflow.com/questions/tagged/pdfkit).

Before posting to StackOverflow, I suggest you closely read [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask) and [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve).

Note that there are two "pdfkit" projects that use the "pdfkit" tag on stackoverflow. One is a JavaScript project (not this project) the other is a ruby project (this project). You will want to be far more explicit about which you are using when you create your question.
