### ISSUE TITLE
thead and tbody contents overlap from second page onwards

### ISSUE THREAD

**Issue by amritshrestha** [pdfkit/pdfkit#357]
I have got thead which is supposed to be repeated to each page. It is working correctly in first page, but from second page onwards contents from tbody is overlaping thead.
I used --margin-top, --header-spacing, but those options only push the content (thead & tbody) downwards creating black space on top of the page.

Anybody have solution to this problem. Any help would be appreciated.
Thanks in advance.

**Comment by sigmavirus24** [comment]
Hi @amritshrestha 

A few things:

1. You do not reference what versions of the software involved you're using (pdfkit or wkhtmltopdf)
1. You're not providing very much detail to help you
1. This is not a support forum but a defect tracker
1. You should be asking for help on [StackOverflow](stackoverflow.com) which *is* the support forum
1. This is likely a problem with wkhtmltopdf and you should be seeking help from that community.
