### ISSUE TITLE
Links with target not working correctly

### ISSUE THREAD

**Issue by aussiDavid** [pdfkit/pdfkit#360]
I have a rails app that generates a pdf for a given html partial. In the partial I have a number of links that have a target of _blank, however in the PDF the target looks like it is being ignored.

I just want the pdf to open the link in a new tab/window.

**Comment by sigmavirus24** [comment]
This sounds like a problem with wkhtmltopdf (which is what renders the pdf from the html). (Pdfkit just wires up everything between ruby/rails and that binary.)

Please ask for help on [StackOverflow](stackoverflow.com) or in the wkhtmltopdf community as they will be more able to help you with their software.

**Comment by aussiDavid** [comment]
Thanks.
