### ISSUE TITLE
PDF Password Protection

### ISSUE THREAD

**Issue by liam-lagay-14** [pdfkit/pdfkit#362]
Hi,

We are looking to use PDF Kit as a possible solution for our application. One of our requirements is Password Protection. Is this a feature that PDF Kit are looking to support at a later date, or would another utility such as PDFtk be recommended?

Thanks,
Liam

**Comment by sigmavirus24** [comment]
PDFkit is merely a wrapper around wkHTMLtoPDF. We don't directly create the PDF. If wkHTMLtoPDF ever adds password protection we would be able to support it. Until then it's not on our road map.
