### ISSUE TITLE
Option --toc failed

### ISSUE THREAD

**Issue by DannyBen** [pdfkit/pdfkit#363]
Hi,

Trying to apply the `--toc` argument, but it fails.

This code:

``` ruby
html = File.read 'in.html'
kit = PDFKit.new html, toc: true
pdf = kit.to_pdf
```

Outputs this error

```
Error: Failed loading page http://toc (sometimes it will work just to ignore this error with --ignore-load-errors)
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:71:in `to_pdf': command failed (exitstatus=0): /home/ubuntu/.rvm/gems/ruby-2.3.1/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 toc - - (RuntimeError)
```

As can be seen towards the end, it just placed `toc` as a file name, instead of placing `--toc` as an argument.

If I change the command to have `--toc` and execute it manually, it works.
- Digging into the code, I see the argument `toc` is [handled differently on purpose](https://github.com/pdfkit/pdfkit/blob/master/lib/pdfkit/wkhtmltopdf.rb#L7)
- Digging into the spec, it looks that the `--` are [removed on purpose](https://github.com/pdfkit/pdfkit/blob/master/spec/pdfkit_spec.rb#L134) - which seems to be an invalid operation (perhaps was applicable to older versions of wkhtmltopdf?).

A bug?

Using wkhtmltopdf 0.9.6:

```
$ wkhtmltopdf --help | grep '\-toc'
  -t, --toc                           Insert a table of content in the beginning
```

**Comment by sigmavirus24** [comment]
So looking at https://github.com/pdfkit/pdfkit/commit/d93fad386c60f7f6e2af6838c2a83af4a5654cfe I think this is to add support for newer versions of wkhtmltopdf (which is way past 1.0). The spec also shows the usage to be different from how you're using it.

**Comment by DannyBen** [comment]
1. The spec shows `pdfkit = PDFKit.new('html', {toc: true})` just in the [next line](https://github.com/pdfkit/pdfkit/blob/master/spec/pdfkit_spec.rb#L140)
2. I have installed wkhtmltopdf using the gem, and this is the version I got.

**Comment by sigmavirus24** [comment]
That wouldn't hurt. We could also attempt to support the versions that removed `--toc` and the versions with it.

**Comment by DannyBen** [comment]
I agree. I am adding PDF support as part of a gem, and I hate to tell people to go find out how to install wkhtmltopdf on their machine. I much rather bundle a gem.

**Comment by sigmavirus24** [comment]
@DannyBen are you up for contributing this code?

**Comment by DannyBen** [comment]
Maybe. Need to familiarize myself with the code first to see where would be appropriate to check for version (+ need to find out which version of the binary is the cutoff version).
