### ISSUE TITLE
undefined method protocol for configuration

### ISSUE THREAD

**Issue by sridhar-bs** [pdfkit/pdfkit#364]
Hi,
Am getting the following error while initializing the pdfkit
**undefined method `protocol=' for #<PDFKit::Configuration:0x000000013f4750> (NoMethodError)**

My config file as below
PDFKit.configure do |config|
  config.wkhtmltopdf = "/usr/local/bin/wkhtmltopdf-amd64"
  config.protocol = 'https'
end
Am using wkhtmltopdf library version 0.9.9

**Comment by sigmavirus24** [comment]
What version of PDFKit are you using?

**Comment by sridhar-bs** [comment]
pdfkit version 0.8.2

**Comment by sigmavirus24** [comment]
You need to install from master to get that option. The change for the README was updated ~6 months ago which is more recent than 0.8.2.

@cdwort we should probably create a new release soon.
