### ISSUE TITLE
Header / Footer text - new lines possible?

### ISSUE THREAD

**Issue by liam-lagay-14** [pdfkit/pdfkit#365]
Hi,

I'm working in Ruby on Rails on a new PDF Generation Service using PDFKit / wkhtmltopdf. 

I've been easily able to set footer_left / centre / right text content no problem. However, if I've tried to then render html_safe text (for example, an I18n translation using a `<br>` tag), it just takes the HTML tag as literal text (doesn't render the HTML correctly). Is this possible to do, or do I need to create custom HTML headers / footers in this case?

Any assistance would be much appreciated in this case.

Thanks,
Liam

**Comment by sigmavirus24** [comment]
That would seem to be strictly a limitation of wkhtmltopdf and you should seek help from that community for the best results.

**Comment by liam-lagay-14** [comment]
Thanks @sigmavirus24,

I was just about to update I worked out I needed to just put a newline in instead of I18n and that got it working, just in case anybody ever came across this issue going forward!
