### ISSUE TITLE
HTML5?

### ISSUE THREAD

**Issue by cwilliamsnh** [pdfkit/pdfkit#366]
Does pdfkit support HTML5?

I'm trying to use some HTML5 CSS features and they seem to be ignored when I generate a PDF from the HTML + CSS.

If needed, I can provide examples.

**Comment by sigmavirus24** [comment]
We support HTML5 if and only if wkHTMLtoPDF supports it.

If you find that wkHTMLtoPDF supports it and you want to contribute some notes that it does support it (and if necessary, how to enable that), feel free to do so!

**Comment by sigmavirus24** [comment]
Otherwise, I'll close this in a couple weeks if we don't hear from you. :)

**Comment by cwilliamsnh** [comment]
Go ahead and close it. If I find anything out, I'll let you know.

Chuck

On Mon, Jul 11, 2016 at 7:02 AM, Ian Cordasco <notifications@github.com>
wrote:

> Otherwise, I'll close this in a couple weeks if we don't hear from you. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pdfkit/pdfkit/issues/366#issuecomment-231704636>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOJjWTFCVc6P_bHZDMleMRDAk_pN20vwks5qUiK0gaJpZM4JJQE1>
> .
>



-- 

Chuck Williams, Software Engineer

Metova Federal, LLC

(703) 338-5162 | www.federal.metova.com
