### ISSUE TITLE
No wkhtmltopdf executable found on Ubuntu 16.04

### ISSUE THREAD

**Issue by euler16** [pdfkit/pdfkit#367]
I installed pdfkit but when I rum pdfkit.from_url it asks me to install wkhtmltopdf (which I did but the problem still exists )
![pdferror](https://cloud.githubusercontent.com/assets/18003525/16761708/f36c4ffa-483e-11e6-9c02-f30456ac5119.png)

**Comment by wutangpaul** [comment]
You're using the python version https://github.com/JazzCore/python-pdfkit

This is for issues relating to the ruby version.
