### ISSUE TITLE
Error: PDF could not be generated!

### ISSUE THREAD

**Issue by sajjadmurtaza** [pdfkit/pdfkit#369]
RuntimeError (Error: Failed to execute:
["/home/ubuntu/app/opx/shared/bundle/ruby/2.2.0/bin/wkhtmltopdf", "-q", "--page-size", "Letter", "file:////tmp/wicked_pdf20160719-16612-1fbcnav.html", "/tmp/wicked_pdf_generated_file20160719-16612-1t9jv2f.pdf"]
Error: PDF could not be generated!

Kindly guide me.

**Comment by sigmavirus24** [comment]
@sajjadmurtaza this is a defect tracker, not a support interaction system. For help with your problems, please use [StackOverflow](https://stackoverflow.com).

I would suggest, however, that you start by running the command as it is printed in the error to find out more information about *why* wkhtmltopdf failed to generate your PDF. It is fundamentally that tool's output that you need to consult in this case.

**Comment by sajjadmurtaza** [comment]
@sigmavirus24 but in my staging server its work fine.

**Comment by sigmavirus24** [comment]
@sajjadmurtaza then the problem is that your staging server and your production server do not match. This is why you [should not have a staging environment](https://alexgaynor.net/2016/jan/19/dont-have-environments/).
