### ISSUE TITLE
PDFKit, with page-break-inside: avoid enabled, fails to not create inside row page breaks on my file.

### ISSUE THREAD

**Issue by joshjacobson** [pdfkit/pdfkit#373]
Example of the problem:

Using PDFKit w/ Python:

```
import pdfkit
options = {
    'user-style-sheet': 'htmltopdf.css'
}

file_p = myfile.html
pdfkit.from_file(file_p, file_p[:-5] + '.pdf', options=options)
```

CSS, htmltopdf.css:

```
<style type="text/css">
tr { 
	page-break-inside: avoid !important;
}

thead, tfoot { 
	display: table-row-group 
}
</style>
```
I've attached the file I'm attempting to work with in which problems occur at page breaks (replace extension w/ .html).

[D - Yadgir_July.txt](https://github.com/pdfkit/pdfkit/files/397514/D.-.Yadgir_July.txt)

**Comment by sigmavirus24** [comment]
The actual rendering of PDFs is done by wkHTMLtoPDF. You should report this there. We just wrap the project to provide a Ruby interface to it.
