### ISSUE TITLE
Request: One-page outputs

### ISSUE THREAD

**Issue by joshjacobson** [pdfkit/pdfkit#374]
As specified in the title, it'd be great to have an option for producing a 1 page .pdf.

There are two possible implementations:

1. Dynamically adjust page-height and page-width such that entire html is on single page of the necessary dimension to contain the entire output. (preferred)

2. Scale down the contents to fit a desired singe page size.

**Comment by sigmavirus24** [comment]
PDFkit delegates actual PDF creation to wkHTMLtoPDF. You should request this on their project and once it supports it, we can look at ensuring we don't get in the way.
