### ISSUE TITLE
Verbose is ignored if default_options are configured

### ISSUE THREAD

**Issue by teeparham** [pdfkit/pdfkit#376]
The default verbose option is true, but that is overridden if default_options are set, as in the readme. Setting `config.verbose = false` does not help either.

```
require 'pdfkit'

PDFKit.configure do |config|
  config.wkhtmltopdf = 'wkhtmltopdf-osx'; 
  config.default_options = {}
  # config.verbose = false # ignored with or without this setting
end

kit = PDFKit.new('x')

kit.command.include?('quiet')
=> false

kit.command
=> "wkhtmltopdf-osx  - -"
```

Workaround: add `quiet` to your default_options:

```
PDFKit.configure do |config|
  # ...
  config.default_options = { quiet: true }
end
```

**Comment by sigmavirus24** [comment]
Ah, yeah, I don't think we test our usage of default_options and we should probably have a custom writer for `default_options` that merges the passed in dictionary instead of flat-out replacing it.

Care to send a PR that does that?
