### ISSUE TITLE
command failed (exitstatus=): /home/a6/.rvm/gems/ruby-2.2.0@gemset/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --print-media-type - -

### ISSUE THREAD

**Issue by AkashkumarDev** [pdfkit/pdfkit#379]
Getting error :
command failed (exitstatus=): /home/a6/.rvm/gems/ruby-2.2.0@gemset/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --print-media-type - -

using Rails 4 , Ubuntu 14.04 and Thin web server. can't generate PDF.
pdfkit = 0.8.2
but i switch to Passenger + Apache2 and then i can generate PDF.

could anyone please help me to know why getting such error on Default Rails web server ?
Thanks

**Comment by hlmerscher** [comment]
https://github.com/pdfkit/pdfkit#troubleshooting
