### ISSUE TITLE
Errno::ENOENT: No such file or directory on to_file

### ISSUE THREAD

**Issue by hendricius** [pdfkit/pdfkit#380]
Having an issue to get PDFKit to work. I can let the wkhtmltopdf command run manually, but when using it via pdfkit I get an error.

The error I get:

```
[1] pry(main)> kit = PDFKit.new('http://google.com').to_file("/tmp/google.pdf")
Errno::ENOENT: No such file or directory @ rb_file_s_size - /tmp/google.pdf
from /home/docking_staging/app/releases/6/vendor/bundle/ruby/2.3.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:190:in `size'
```

My initializer:
```
PDFKit.configure do |config|
  config.wkhtmltopdf = ENV['WKHTMLTOPDF_PATH'] || "/usr/local/bin/wkhtmltopdf"
  config.verbose = true
end
```

My launch script for wkhtmltopdf:

```
#!/bin/bash
WKHTMLTOPDF="/usr/local/bin/wkhtmltopdf"

xvfb-run /usr/local/bin/wkhtmltopdf $@
```

Same error also happens if I just pass an html string to the engine.

Thanks!

**Comment by dsfernandobond** [comment]
Did you ever solve this? Having the same problem.

**Comment by entersoftapps** [comment]
`sudo apt-get install fontconfig`

**Comment by smocaine** [comment]
I'm running into this problem as well. Has anyone figured this out?

**Comment by schappim** [comment]
I can confirm I'm having the same issue on Ubuntu. 

@entersoftapps this issue is unrelated to fontconfig.

**Comment by smocaine** [comment]
I figured out the problem in my case. I didn't have `config.threadsafe!` in development.rb.

**Comment by chizelcoco** [comment]
I am also facing this problem in my production environment. In development env I had to add write permissions to the folder, to be able to write a new file to the specified directory to resolve this. But not able to resolve this in production. Any solutions?

**Comment by serene** [comment]
@chizelcoco Perhaps you should try writing to the tmp file in the rails directory instead?

For example:
`File.join(Rails.root,'tmp','myfile.pdf')`
