### ISSUE TITLE
Is there a way to log the exact command sent to wkhtmltopdf?

### ISSUE THREAD

**Issue by paulrosen** [pdfkit/pdfkit#383]
I think I figured out the command that is being sent to wkhtmltopdf, but I'm getting different results when running wkhtmltopdf from the command line and when I run PDFkit as middleware, so I'm trying to debug what is different about the call.

(Note: when running from the command line, the PDF is generated correctly, with background images, but, when running through middleware, the background images are missing.)

Is there a way I can figure out exactly what PDFkit is sending to wkhtmltopdf? It would be convenient if it were printed to the Rails production.log file.

**Comment by sigmavirus24** [comment]
If you know how a PDFKit instance is being created, you can do 

```rb
pdfkit = PDFKit.new(...)
puts(pdfkit.command)
```

I don't think we do anything to log this for folks, although adding that may be a worthwhile endeavor.

**Comment by paulrosen** [comment]
For my debugging purposes, I hacked into pdfkit.rb and added the following to the "command" method:

```
open('/.../log/pdfkit-commands.log', 'a') { |f|
  f.puts "#{shell_escaped_command} #{input_for_command} #{output_for_command}"
}
```

That helped me to isolate my specific problem. It does seem like having that as part of the gem would be nice for other folks.
