### ISSUE TITLE
Support ignore error option

### ISSUE THREAD

**Issue by egh** [pdfkit/pdfkit#392]
When `wkhtmltopdf` exits with non-0 exit status, pdfkit will (generally) throw an exception.

This is not always ideal. See, e.g. the upstream bug https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3380

It would be nice to have an option to pdfkit to ignore (that is, not raise an exception) for non-0 exit statuses that nonetheless generate a PDF.

**Comment by ownadi** [comment]
It could be useful feature. I created a pr (https://github.com/pdfkit/pdfkit/pull/395) that adds this ability.
