### ISSUE TITLE
pdfkit + Chartkick - Not load

### ISSUE THREAD

**Issue by PedroPauloML** [pdfkit/pdfkit#398]
Hi!
I'm get the error when I request to generate the pdf, but the graph of Chartkick not load.

![captura de tela 18](https://user-images.githubusercontent.com/21173324/27874053-9289ef98-6184-11e7-9fc4-56c40f34bf08.png)

Any tips?

**Comment by serene** [comment]
Sometimes third-party javascript files take some time to load. You can increase the javascript-delay wait time in the wkhtmltopdf options.

You can see all the options here: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

Set wkhtmltopdf options either in the pdfkit.rb as default options, or in your template with

'PDFKit.configure do |config|
  config.wkhtmltopdf = ENV['WKHTMLTOPDF_PATH']
  config.default_options = {
      :javascript_delay => '2000'
  }
end'

`<meta name="pdfkit-javascript-delay" content="5000/>`

This is not a problem with pdfkit, so I am closing this issue.
