### ISSUE TITLE
RuntimeError - command failed (exitstatus=): /bin/wkhtmltopdf --encoding UTF-8 --page-size A4 --print-media-type --header-html http://localhost:3002/pdf-header.html --margin-top 1.2 --margin-bottom 1.2 - -:

### ISSUE THREAD

**Issue by pooja-mane** [pdfkit/pdfkit#402]
I am using _pdfkit_ gem version 0.8.2
I have added binary file for _wkhtmltopdf_ of version 0.12.2.1
ubuntu 14.04 LTS
Whenever I am going to add header and footer in pdf it gives me error as _command_ failed.
I have tried for gem 'wkhtmltopdf-binary' and even for system 'wkhtmltopdf' for ubuntu also.
Can any one tell us what is wrong ?
Thank you.

**Comment by serene** [comment]
Are you getting an error without adding the header? If so, then it's most likely not an issue with wkhtmltopdf, but something wrong in the header HTML. Try using pdf-header.html directly instead of going through your web server. If that doesn't work, make the header as simple as possible first (one line of text) and then expand from there. This should help you to pinpoint where the problem lies.

Hope you are able to find the issue!

**Comment by av-abennacer** [comment]
I got the exact same issue using pdfkit and wkhtmltopdf with same versions.
I tried without adding an header to my pdf, still doesn't work.
@pooja-mane did you find a solution ?

**Comment by serene** [comment]
@av-abennacer Try running wkhtmltopdf on the command line, and see if you get an error there.

**Comment by abdulrahman-ahmad** [comment]
I had the same issue but I had port forwarding for environment purposes.
Using the default rails 3000 port fixed that part for me.
Not sure if that's the same case as yours, but I had Connection Refused exception with that as well.

**Comment by mlhamel** [comment]
I've got the same issue and sadly seems to work as it should from the command line :-/

**Comment by aruprakshit** [comment]
I am getting the same error. Why the existstatus is blank? I am on `wkhtmltopdf 0.12.2.1 (with patched qt)`

**Comment by VoTaiTri** [comment]
You can check [Resources aren't included in the PDF](https://github.com/pdfkit/pdfkit#troubleshooting) on troubleshooting here, maybe failure when loading file

**Comment by serene** [comment]
If you are receiving the same error with wkhtmltopdf, then it is an issue on wkhtmltopdf. Keep in mind that pdfkit is just a wrapper for the library.
