### ISSUE TITLE
Generate invalid PDF when using an embedded TTF font

### ISSUE THREAD

**Issue by ianbale** [pdfkit/pdfkit#408]
I am using an embedded Truetype font.

Although the generated PDF looks fine in the browser. If I save it to disk and try to open is in a PDF viewer I find that it will not open. I have tried in Mac Preview and Acrobat Pro. 

Using the PDF validator tool www.pdf-online.com/osa/validate.aspx I get this output

```
Compliance | pdf1.3
Result | Document does not conform to PDF/A.
Details | Validating file "eTicket.pdf" for conformance level pdf1.3
The "endobj" keyword is missing.
The key Encoding is required but missing.
The key DescendantFonts is required but missing.

The document does not conform to the requested standard.

The document doesn't conform to the PDF reference (missing required entries, wrong value types, etc.).
The document does not conform to the PDF 1.3 standard.
```
NOTE: I am using two embedded fonts. The ATOC font and Calibri. If I remove the ATOC font and use only the Calibri one, then the generated PDF is ok.

I have used the Microsoft Font Validation tool to check the font. It does have a few glyph overlap issues, but is otherwise perfectly valid. I am also aware that this font is being used by another company with a different PDF generator without issue. So it does not look like the fault lies with the Font.

I've enclosed the Font file and the generated PDF for reference.

[Archive.zip](https://github.com/pdfkit/pdfkit/files/1379099/Archive.zip)

**Comment by serene** [comment]
Have you tried by directly invoking wkhtmltopdf on the HTML file?

Font issues are often resolved by including fullpath urls to the font file.

I'll be closing this issue as it has gone stale, but will be happy to reopen it if more information arises.
