### ISSUE TITLE
Draw SVG on PDF with pdfkit gem

### ISSUE THREAD

**Issue by imtiaz-emu** [pdfkit/pdfkit#413]
Could you please give me any idea how to do this? I've asked a question on statckoverflow:

https://stackoverflow.com/questions/47671188/draw-svg-on-pdf-with-pdfkit-gem

**Comment by spovich** [comment]
@imtiaz-emu I'm having a similar issue.  Have you made any progress on this or taken a different approach?

**Comment by imtiaz-emu** [comment]
@spovich I switched to **wickedpdf** gem. Added gem 'wicked_pdf', gem 'wkhtmltopdf-binary-edge', '~> 0.12.4.0' in gemfile. Then installed `wkhtmltopdf` in server (https://gist.github.com/brunogaspar/bd89079245923c04be6b0f92af431c10). 
In controller used:
```
pdf = WickedPdf.new.pdf_from_string(as_html)
      save_path = Rails.root.join('public', 'yearly_report.pdf')
      File.open(save_path, 'wb') do |file|
        file << pdf
end


private

  attr_reader :results

  def as_html
    render_to_string(template: "reports/generate_pdf.html.erb", layout: false, locals: {results: results})
end
```

**Comment by spovich** [comment]
@imtiaz-emu thank you!  I'll try that out!
