### ISSUE TITLE
Middleware does not conform to Rack SPEC

### ISSUE THREAD

**Issue by wagenet** [pdfkit/pdfkit#414]
The [spec states](http://www.rubydoc.info/github/rack/rack/file/SPEC#The_Body): 

> If the body is replaced by a middleware after action, the original body must be closed first, if it responds to close.

However, we can see that this does not happen:
https://github.com/pdfkit/pdfkit/blob/master/lib/pdfkit/middleware.rb#L19

**Comment by wagenet** [comment]
I believe this is still an issue, though the line number is no longer accurate.

**Comment by wagenet** [comment]
@serene not sure if you're the right person to handle this, but I believe this is still an issue.

**Comment by serene** [comment]
@wagenet Can you throw together a quick PR?
