### ISSUE TITLE
ContentNotFoundError

### ISSUE THREAD

**Issue by GildedHonour** [pdfkit/pdfkit#416]
I have the error "ContentNotFoundError". It's due a bug in the C++ library https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2051

How to fix it for this gem? They've mentioned a workaround there but that's for C++

**Comment by unkemptArc99** [comment]
I have also been facing the same problem. I tried to catch the exception OSError, but it seems that this very exception is thrown in many other errors as well.

**Comment by serene** [comment]
pdfkit is just a wrapper for wkhtmltopdf. If there is a bug with that library, then you will need to wait for a bug fix and update that library.
