### ISSUE TITLE
support wkhtmltopdf 0.12.4

### ISSUE THREAD

**Issue by artempartos** [pdfkit/pdfkit#418]
subj

**Comment by map7** [comment]
I have pdfkit working with 0.12.5 (system installed on a Debian Jessie & Stretch machine). It works in tests and production, here is my setup;

https://github.com/pdfkit/pdfkit/wiki/Adding-header-and-footers

**Comment by serene** [comment]
wkhtmltopdf 0.12.4 is already supported. Closing this issue.
