### ISSUE TITLE
html_header doesn't appear

### ISSUE THREAD

**Issue by GomesAle** [pdfkit/pdfkit#420]
When I try to generate the pdf from html, the header doesn't appear. The footer is ok.

Example:

#main.rb (ruby file that generates the pdf file)
```
require 'pdfkit'
x = File.new('layout.html')
kit = PDFKit.new(x, :footer_html => 'footer.html', :header_html => 'header.html',:page_size => 'A4')
file = kit.to_file('out1.pdf')
```

#layout.html
```
<meta charset="utf-8" />
<html><body>Hi!</body></html>
```
#footer.html
```
<meta charset="utf-8" />
<div><div class="bold">Footer</div>Footer</div>
```

#header.html
```
<meta charset="utf-8" />
<div><div class="bold">Header</div>Header</div>
```

How to make the header apppear?
Thanks

**Comment by serene** [comment]
Have you tried it on the command line with just wkhtmltopdf to see if that works?
Do you receive any error messages?

**Comment by GomesAle** [comment]
@serene Thanks for your help.
I solved the problem adding '<!doctype html>' in the beggining of header.html file.
