### ISSUE TITLE
Zipping a pdf file

### ISSUE THREAD

**Issue by josephchan91** [pdfkit/pdfkit#422]
Hi,

Thanks for this super helpful library!

I have an API that accepts transaction data and generates two files: 1 excel file and 1 pdf file. I'd like to zip these together into a folder for the client to download. I've tried using [node-zip](https://github.com/daraosn/node-zip) and [node-archiver](https://github.com/archiverjs/node-archiver). However, when I download and open the zip file, I see that the pdf file is 0kb (can't open), while the excel file works fine. Any tips?

Thanks!
Joseph

**Comment by serene** [comment]
Is this a pdfkit specific question?

**Comment by bso-oo** [comment]
> Hi,
> 
> Thanks for this super helpful library!
> 
> I have an API that accepts transaction data and generates two files: 1 excel file and 1 pdf file. I'd like to zip these together into a folder for the client to download. I've tried using [node-zip](https://github.com/daraosn/node-zip) and [node-archiver](https://github.com/archiverjs/node-archiver). However, when I download and open the zip file, I see that the pdf file is 0kb (can't open), while the excel file works fine. Any tips?
> 
> Thanks!
> Joseph

hi 
Did you solve this problem?
