### ISSUE TITLE
Command Failed, Exit code 127, runs in shell and development but not production

### ISSUE THREAD

**Issue by Ekkstein** [pdfkit/pdfkit#423]
Hello,

I hope this is just a configuration problem on my part. Thank you for your time looking at my problem.

I am running a rails application in Version 5.1.3 on a ubuntu machine with nginx and passenger.
In my code i am running: 

`PDFKit.new(my_html_string).to_pdf`

I have confirmed, that my html is simple and has no references.
I have confirmed, that the wkhtmltopdf binary is referenced correctly.
The pdf is correctly generated, if I run the same command from the rails console in production environment. The same command also works in development. 
It just doesn't work from within the passenger app server.
I have kept all options at default, this is the error from my production.log
`RuntimeError (command failed (exitstatus=127): /path_to_app/shared/bundle/ruby/2.4.0/bin/wkhtmltopdf --page-size Legal --print-media-type - -):`
I do not know, if IO.popen was successful, or if my result is empty. 

I have spend several hours with this issue and am stuck right now. I am one step away from injecting debugging code in the pdfkit source to get unstuck...please help, thread safety and stati handling is a little too much for me right now.

**Comment by Ekkstein** [comment]
I have spent several more hours trying to figure out what's going on. The successful?($?) is false. It's exit code is 127 meaning something like the file wasn't found. However, the `which wkhtmltopdf` returned the bundles executable path and a File.exists?(path_to_wkhtmltopdf) also returns true.
Now I am really stuck. Please help...

**Comment by Ekkstein** [comment]
I finally got it to work. It was a combination of things. Mismatching wkhtmltopdf version, Passengers PATH, RBENV GEM Environment...it seems like I still don't understand the whole complexity and the workings of all the parts intertwined. I'll close this issue. If anybody runs into a 127 executing the to_pdf function, I recommend testing the responsiveness of wkhtmltopdf on your system with a command like this:  puts (or log somehow) `wkhtmltopdf -V 2>&1`. The -V option just returns the version of the binary, the 2>&! will also return the commands STDERR output which you can then inspect in your log.

**Comment by ipepe** [comment]
If anyone else stumbles here for me the reason was missing shared libraries. Relevant StackOverflow here: https://stackoverflow.com/questions/5035601/rails-error-running-wkhtmltopdf-error-while-loading-shared-libraries

Solution: `sudo apt-get install libXrender libXext fontconfig`
