### ISSUE TITLE
wkhtmltopdf exited with non-zero code -15. error:

### ISSUE THREAD

**Issue by rohit-taneja** [pdfkit/pdfkit#424]
Can you tell the meaning of exit code 15 OR When will someone get this error ?

# Software Info:

- OS : Ubuntu 14.04.3 LTS
- wkhtmltopdf : 0.12.2.1 (with patched qt)
- pdfkit : 0.6.1
- python : 3.4.3

**Comment by serene** [comment]
This is a pretty standard message. Can you provide some context to when you're receiving this error?
