### ISSUE TITLE
The pdf contains decoded html even though the input is encoded

### ISSUE THREAD

**Issue by SaitejaP** [pdfkit/pdfkit#427]
pefkit - 0.6.1
wkhtmltopdf - 0.12.4
platform - linux

```
import pdfkit
pdfkit.from_string('&#x3C;script src=&#x22;https://sehacure.xss.ht&#x22;&#x3E;&#x3C;/script&#x3E;', '<file_path>')
```

Actual Output:
![image](https://user-images.githubusercontent.com/6340565/47951601-da8cb180-df88-11e8-8874-bf0dbf90b623.png)

Expected Output:
`&#x3C;script src=&#x22;https://sehacure.xss.ht&#x22;&#x3E;&#x3C;/script&#x3E;',` in pdf

I am not sure whether this issue is solely with wkhtmltopdf or in calling wkhtmltopdf by pdfkit.

**Comment by serene** [comment]
@SaitejaP Can you test with wkhtmltopdf directly first to ensure that this is an issue with pdfkit?
