### ISSUE TITLE
Is PDFKit no longer being maintained?

### ISSUE THREAD

**Issue by dougc84** [pdfkit/pdfkit#428]
There hasn't been any changes to master in 3+ years, and many PRs and issues have been addressed by members of the PDFKit team, but no one seems to have access to publish the gem.

What gives guys?  At least post something on the README.

**Comment by serene** [comment]
I just requested push access last week and will be doing some security updates on the weekend.

It is an open source project that people work on when they are able to contribute. If you would like to dedicate some time to help out, we'd be happy to have extra hands on deck.

**Comment by dougc84** [comment]
Hey @serene - Thanks for the response.  I would be happy to contribute, but there are also 18 open pull requests along with several dozen open issues without responses.  Without PDFKit being a stable project on Rails 5, I'll continue keeping an eye on this project, but I've moved on to `wicked_pdf`.

Good luck with the project - it'll be good to have some maintainers on board.
