### ISSUE TITLE
missing  image in headers on some pages randomly

### ISSUE THREAD

**Issue by navkumar2245** [pdfkit/pdfkit#430]
hax = SecureRandom.hex(10)
      name = "pdf/#{hax}.html"
      logo = @hash[:a_logo] 
      ss = Rails.public_path.join(name)
      header_new = render_to_string(:partial => "pdf/header", :locals => {:logo => logo}, layout: false)
      file =  File.new(ss,'w')
      file.write(header_new)
      file.rewind

head = req_base_url + "/pdf/#{hax}.html"   #read header.html for pdf
      header = URI(head)

      foot = req_base_url + "/pdf/footer.html"  #read footer.html for pdf
      footer = URI(foot)
      newcont = content.dup
      header_new  = req_base_url + "/pdf/header.html"
      kit = PDFKit.new(newcont, :page_size => 'Letter', :header_html => header, :header_spacing =>5, :footer_html => footer) 
      kit.stylesheets << 'app/assets/stylesheets/pdf.css'
path = "#{Rails.root}/tmp/" + @engagement.id.to_s + "_file.pdf"

      # path = Rails.public_path.join(name)
      pdf_file = kit.to_file(path)

######### header html
<!DOCTYPE html><p style="margin:0;padding:0;position:relative;height:50px; width:100%;"><center><img src="<%= logo %>" style="max-height:50px; max-width:200px;"/></center></p>

#### initializer for pdfkit
PDFKit.configure do |config|
#   config.wkhtmltopdf = 'bin/wkhtmltopdf' if Rails.env.production?
config.wkhtmltopdf = "#{Rails.root}/bin/wkhtmltopdf"

end

**Comment by navkumar2245** [comment]
my rails server are running behind elastic load balancer with two ec2 instances when i configure load balancer to use only 1 instance logo on pdf appear on all pages but when i use two instance it started disappearing on some pages randomly.

**Comment by serene** [comment]
This is a DevOps image path issue, not an issue with pdfkit.
