### ISSUE TITLE
New version 0.8.3 missing from source code

### ISSUE THREAD

**Issue by niels-s** [pdfkit/pdfkit#431]
Hey there,

one of our project just got a PR by [Dependabot](https://dependabot.com/) to update pdfkit gem to the latest 0.8.3 version which has been released to rubygems. But when I check this repository I can't find any reference to that version, 0.8.3 being release.
Nothing in the CHANGELOG.md, the Github releases or the tags and when I check the version file it's still on 0.8.2 https://github.com/pdfkit/pdfkit/blob/dca550e218ea90e27f7a4975731b596a86cce133/lib/pdfkit/version.rb#L2
Did somebody forget to commit the version bump?

**Comment by serene** [comment]
My apologies. Fixed in #432.
