### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by abhishek77in** [pdfkit/pdfkit#443]
I am generating PDF using the method mentioned in wiki - https://github.com/pdfkit/pdfkit/wiki/Adding-header-and-footers

I feel since the PDFKit config is modified this is **not thread safe**. I am running `sidekiq` with concurrency `2` and I already getting mixed output. The PDF are generated with the right body content but the `header` and `footer` came from another PDF. 

Is there a way to mention `header_html` in an instance variable instead of the constant `PDFKit`.

```  
def config
    PDFKit.configure do |config|
      config.wkhtmltopdf = "/usr/local/bin/wkhtmltopdf"

      config.default_options = {
        encoding:"UTF-8",
        dpi: '300',
        margin_top: '30',
        margin_bottom: '23',
        margin_left: '10',
        margin_right: '10',
        header_spacing: '0',
        header_html: render_header_footer("header"),
        footer_spacing: '2',
        footer_html: render_header_footer("footer"),
        quiet: true,
        :"user-style-sheet" => "#{Rails.root}/app/assets/stylesheets/pdfkit.scss"
      }
    end
  end
```

I have different `header` and `footer` for every PDF document generated.

**Comment by abhishek77in** [comment]
Changed my code to use:

```
    kit = PDFKit.new(as_html,
                      header_html: render_header_footer("header"),
                      footer_html: render_header_footer("footer"))
    kit.to_pdf
```

I believe this should solve the problem.

**Comment by serene** [comment]
Can you create a test to reproduce this problem?

**Comment by abhishek77in** [comment]
I am not sure if this needs testing. Modifying constant like that will cause issues and should not be done. This method is not officially suggested by pdfkit, so if we just update the wiki it should do.

**Comment by gi** [comment]
Can this be closed?

**Comment by serene** [comment]
I don't think it's really an issue? Just a documentation update if someone wants to add it.

**Comment by abhishek77in** [comment]
Thread safety issue is very critical. Yes, just the documentation update is required.

**Comment by abhishek77in** [comment]
Someone can update the documentation or I can do it. Then we can close this for sure.
