### ISSUE TITLE
Create missing tags for new versions

### ISSUE THREAD

**Issue by onshi** [pdfkit/pdfkit#452]
Hello! Awesome job maintaining this gem 🙇 

@serene would you consider pushing missing tags for released versions of the gem? 

I believe that:
v0.8.3 -> a18b4276708a0bf08c7468beffbe228307558c74
v0.8.4 -> 5bbda8491ea3ed7b1f555102bc0641c85ca82b2f

Cheers!

**Comment by serene** [comment]
Done. Thanks for your patience.
