### ISSUE TITLE
Mirror margins or inside margins for book creation

### ISSUE THREAD

**Issue by GaragusoPD** [pdfkit/pdfkit#456]
I've been trying to get PDFkit to respect "inside" and "outside" margins when exporting a PDF, but can't get it done. Left and Right pages need to have different inside and outside margins for binding purposes, but when the page is auto generated, it inherits the margins from the "parent" page. Thus, a right page that bleeds content on a "left" page will keep the same margins as the previous page. I've tried using the "pageAdded" event to capture the page creation and modify the margins on the fly, but the automatic page added already sets content on the page with the "bleeded text" from the previous page.
I'm using NodeJS.
Any idea if it's possible to alter this behavior?

**Comment by serene** [comment]
This is a ruby gem that wraps wkhtmltopdf. How are you using this with NodeJS?

**Comment by GaragusoPD** [comment]
Sorry, wrong PDFkit repository
