### ISSUE TITLE
Pdf output is garbled

### ISSUE THREAD

**Issue by MilamBardo** [pdfkit/pdfkit#458]
On my node project, I wanted to run np audit.  This required a new version of npm.  Upon running the audit, I then needed to update a lot of npm modules, and also upgraded node from 6.92 to 12.3.1.

My pdfs were working fine before this.

This is the output I now get on my pdf:

`%PDF-1.3
%ÿÿÿÿ
7 0 obj
<<
/Type /Page
/Parent 1 0 R
/MediaBox [0 0 612 792]
/Contents 5 0 R
/Resources 6 0 R
>>
endobj
6 0 obj
<<
/ProcSet [/PDF /Text /ImageB /ImageC /ImageI]
/Font <<
/F1 8 0 R
>>
>>
endobj
5 0 obj
<<
/Length 220
/Filter /FlateDecode
>>
stream
xœµQ1N1ìó
€`;öx#¶@‚‚)¢8¶»‚ÿ7x$ÄmÃ$ÒX±¬ñÌDˆóÞHBt¥Ó¹|ÙôîÆwS(˜0µÚ&£q.·B¢4–ò|ð††	Ç	®l	ƒ·ãLÎtPVnÚ¸Iëú–¨”™ø…Æc¹åé/ûÑ«¯[ïWÞËã^±±a«‰%8º—Ò¤¦kÎ´ÜÛ1‘×œÑÑfÒŒ¯á‘=è×;Y/±á=g2ÆœÖ¬¶W‰F:6J2ô%f¡«W,Èó*Ä*ë&ã«¯ú=]‚ú
endstream
endobj
10 0 obj
(PDFKit)
endobj
11 0 obj
(PDFKit)
endobj
12 0 obj
(D:20191210115354Z)
endobj
9 0 obj
<<
/Producer 10 0 R
/Creator 11 0 R
/CreationDate 12 0 R
>>
endobj
8 0 obj
<<
/Type /Font
/BaseFont /Helvetica
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
4 0 obj
<<
>>
endobj
3 0 obj
<<
/Type /Catalog
/Pages 1 0 R
/Names 2 0 R
>>
endobj
1 0 obj
<<
/Type /Pages
/Count 1
/Kids [7 0 R]
>>
endobj
2 0 obj
<<
/Dests <<
  /Names [
]
>>
>>
endobj
xref
0 13
0000000000 65535 f 
0000000841 00000 n 
0000000898 00000 n 
0000000779 00000 n 
0000000758 00000 n 
0000000208 00000 n 
0000000119 00000 n 
0000000015 00000 n 
0000000661 00000 n 
0000000586 00000 n 
0000000500 00000 n 
0000000525 00000 n 
0000000550 00000 n 
trailer
<<
/Size 13
/Root 3 0 R
/Info 9 0 R
/ID [<b71dfad3855e83b1a78a437713c07e4e> <b71dfad3855e83b1a78a437713c07e4e>]
>>
startxref
945
%%EOF`

This is my package.json dependencies:

`"dependencies": {
    "@types/express": "^4.17.2",
    "@types/morgan": "^1.7.37",
    "@types/request": "^2.48.3",
    "@types/serve-favicon": "^2.5.0",
    "@types/shelljs": "^0.8.6",
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.4",
    "core-js": "^3.4.8",
    "debug": "^2.6.9",
    "express": "^4.17.1",
    "fs": "0.0.1-security",
    "fs-extra": "^8.0.1",
    "helmet": "^3.21.2",
    "http-proxy-middleware": "^0.20.0",
    "jade": "^1.11.0",
    "morgan": "^1.9.1",
    "node": "^13.3.0",
    "nodemon": "^1.19.1",
    "npm-run-all": "^4.1.5",
    "pdfkit": "^0.10.0",
    "request": "^2.88.0",
    "rimraf": "^2.6.3",
    "serve-favicon": "^2.5.0",
    "shelljs": "^0.8.3",
    "ts-node": "^8.2.0",
    "typescript": "^3.7.3"
  },`

Here's how I'm generating pdf:

`var PDFDocument = require('pdfkit');
    var fs=require('fs');
    var doc = new PDFDocument();
    doc.pipe( fs.createWriteStream('out.pdf') );  

      let xval : number = 70
      let yval : number = 100

      doc.text("Employee:  "+schedule.name, xval, yval)
      yval += 25;

      doc.text("Schedule Date:  "+schedule.scheduledate, xval, yval)

      doc.text("  ")
      for (var ins of schedule.scheduleinstructions)
      {
        yval += 25;
        doc.text(ins.time + "  "+ ins.instruction)
        doc.text("  ")
      }
    
    doc.pipe( res );
    doc.end();`

Any ideas as to the problem?

**Comment by MilamBardo** [comment]
Figured it out.

It was actually helmet which was causing the problem.  

I just had to get rid of this line:

app.use(helmet())

**Comment by serene** [comment]
Closing this issue since the problem was solved.
