### ISSUE TITLE
0.8.4.2 install problem

### ISSUE THREAD

**Issue by durdenk** [pdfkit/pdfkit#468]
I cant find this package using pip,
I tried to install from source and I ran
pip install https://github.com/pdfkit/pdfkit/archive/v0.8.4.tar.gz
I got the following error. Is it a known problem?

    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-35v6ijlx/setup.py'
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by fernandoluizao** [comment]
This is not a python package... maybe you are looking for [this](https://github.com/JazzCore/python-pdfkit)?
