### ISSUE TITLE
Upgrade from 0.8.4.1 -> 0.8.4.3.1 causing ENOENT errors when calling File.size

### ISSUE THREAD

**Issue by taylorthurlow** [pdfkit/pdfkit#478]
I upgraded from `0.8.4.1` to `0.8.4.3.1` (on wkhtmltopdf `0.12.5`) and I started getting this error when generating a PDF:

`Errno::ENOENT: No such file or directory @ rb_file_s_size`

This is `pdfkit/pdfkit.rb` @ line 150, which is

```
(path && File.size(path) == 0) || (path.nil? && result.to_s.strip.empty?)
```

It's choking on the `File.size(path)` as far as I can tell. Any idea why this might be?

**Comment by yigger** [comment]
@taylorthurlow i got the same problem, any solutions?

**Comment by taylorthurlow** [comment]
@yigger I poked around to see if I could remember where I had this issue, or find where this error got logged, but I couldn't find it. 

Some part of me is thinking that it ended up just being the fact that some change to pdfkit meant that the "hey this file is missing" error ended up being this instead of whatever it was before.

Sorry I couldn't be of more help.

**Comment by yigger** [comment]
@taylorthurlow Ok, thank you for your reply.
