### ISSUE TITLE
URI::escape and URI::decode are deprecated in Ruby 3

### ISSUE THREAD

**Issue by davidtansf** [pdfkit/pdfkit#500]

**Comment by davidtansf** [comment]
NoMethodError: undefined method `decode' for URI:Module
NoMethodError: undefined method `escape' for URI:Module

**Comment by technicalpickles** [comment]
https://github.com/pdfkit/pdfkit/pull/499 is a PR to fix this

**Comment by technicalpickles** [comment]
This is still a problem.

**Comment by jeantristan** [comment]
This is still a problem
