### ISSUE TITLE
Vulnerabilities found!

### ISSUE THREAD

**Issue by adiln** [pdfkit/pdfkit#514]
Hi  Team,

Our one of the apps consuming this gem. I found this vulnerability. Can you please have a look?
<img width="928" alt="image" src="https://user-images.githubusercontent.com/1119246/193538596-da16e727-c34c-4d84-a6b6-8df5fa0ecaa6.png">

**Comment by kiafaldorius** [comment]
Not resolved. The fix in #509  isn't enough see #517

**Comment by adiln** [comment]
Thanks a lot!, this is resolved.
