### ISSUE TITLE
wkhtmltopdf is deprecated by its author

### ISSUE THREAD

**Issue by karelbilek** [pdfkit/pdfkit#526]
wkhtmltopdf is deprecated by its author and is no longer maintained.

I think it should be at least mentioned here.

See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5160

I think the author no longer recommends it for use.

**Comment by raghuvarmabh** [comment]
any update on this? If anybody found any alternatives/workarounds to replace `wkhtmltopdf`  please post here. Thanks!
