### ISSUE TITLE
Exit with code 1 due to network error: ProtocolUnknownError

### ISSUE THREAD

**Issue by theqa-ninja** [pdfkit/pdfkit#527]
Currently on 
Mac OS 12.6
Intel CPU
ruby 3.1.1
pdfkit 0.8.7.2
wkhtmltopdf-binary 0.12.6.6

Here's my code
```
kit = PDFKit.new(File.new("results/temp.html"), :page_size => 'Letter')
pdf = kit.to_pdf
file = kit.to_file("results/temp.pdf")
```

the `temp.html` is just a webpage I render with no javascript

this throws the error

```
Exit with code 1 due to network error: ProtocolUnknownError
/Users/moi/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pdfkit-0.8.7.2/lib/pdfkit/pdfkit.rb:79:in `to_pdf': Command failed (exitstatus=1): ["/Users/moi/.rbenv/versions/3.1.1/bin/wkhtmltopdf", "--quiet", "--page-size", "Letter", "--margin-top", "0.75in", "--margin-right", "0.75in", "--margin-bottom", "0.75in", "--margin-left", "0.75in", "--encoding", "UTF-8", "results/bbb.html", "-"] (PDFKit::ImproperWkhtmltopdfExitStatus)
```

Help please, not sure why i'm getting the network error opening a local webpage

**Comment by alex-jerez** [comment]
I noticed this happens when the HTML file references a `url()` in the CSS. In my instance, this line in my CSS caused this issue

```
background-image: url("image.png");
```

if you have any image embeds like that, try commenting them out to see if that's the problem. If it is, set  `enable-local-file-access` to false in your pdfkit settings and that should fix it.

**Comment by alexsro** [comment]
I'm facing the same problem do you solved this? @theqa-ninja

**Comment by regismesquita** [comment]
I have found a fix, you have to enable local file access, as in:
```
    kit = PDFKit.new(html, :page_size => 'Letter', :enable_local_file_access => '/full/path/to/image.png' )
```

**Comment by regismesquita** [comment]
The above caused an empty page to be added to my final file, I ended up adding the content using base64.
