### ISSUE TITLE
Error when trying to convert to pdf

### ISSUE THREAD

**Issue by amcmillion3** [pdfkit/pdfkit#532]
I am trying to convert html to a pdf and I am getting this error. 
`PDFKit::ImproperWkhtmltopdfExitStatus (Command failed (exitstatus=255): /usr/local/bundle/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --enable-local-file-access - -)`

I have looked all over and can't find anything useful. Any help would be appreciated.

**Comment by bugamehmet** [comment]
Missing or misconfigured wkhtmltopdf tool: Ensure that the wkhtmltopdf tool is installed and properly configured. If it's not installed, download the appropriate version from the website and install it.

Incorrect input HTML content: There might be some invalid or broken code or links in the HTML content you are trying to convert to PDF. Review the HTML content and try to identify any possible errors.

Permissions issue with wkhtmltopdf: Check the permissions of the wkhtmltopdf tool and the files you are trying to operate on. If there are read or write permissions issues, the conversion process may fail.

Directory or file name issues: There could be incorrect characters or missing parts in the file paths or names. This might be preventing the conversion process.

wkhtmltopdf version incompatibility: The version of wkhtmltopdf you are using might be incompatible with PDFKit or other dependencies in your project. Trying a different version of wkhtmltopdf may help resolve the issue.

**Comment by ptolemybarnes** [comment]
This is likely due to recent versions of wkhtmltopdf disabling local file access by default. You can work around it by configuring PDFKit like:

```ruby
PDFKit.configure do |config|
      config.default_options = {
        :enable_local_file_access => true
      }
end
```

I've opened a PR to add this as a default option: https://github.com/pdfkit/pdfkit/pull/533
