### ISSUE TITLE
wkhtmltopdf is deprecated and no longer recommended

### ISSUE THREAD

**Issue by ragingdave** [pdfkit/pdfkit#540]
Is there any plans to update this to either allow another pdf generator (weasyprint or other alternatives) on top of wkhtmltopdf?

This seems like a living-dead gem if it's only able to support a generator that itself no longer is recommended, and the latest version isn't even available in distribution repositories.

On it's surface it seems like swapping the binary would be the path forward but are there any gotchas going that route?

**Comment by paddor** [comment]
Any more info on this?
