### ISSUE TITLE
PDFKit not working in ruby console?

### ISSUE THREAD

**Issue by angelacode** [pdfkit/pdfkit#73]
I currently get the following:

```
>> require 'pdfkit'
MissingSourceFile: no such file to load -- pdfkit
```

I read the following and followed it, but still no luck:

http://www.42.mach7x.com/2010/10/28/no-such-file-to-load-pdfkit-loaderror/

I want to get it working in the console before I code the app to make sure I understand whether it can do what I want it to do.

**Comment by sebastialonso** [comment]
Same issue here,
`require 'pdfkit'` does nothing when trying on terminal

**Comment by cdwort** [comment]
Hi @sebastialonso 

This is a closed issue. If you are still getting the same error, can you create a new issue and paste in the output after running the command?
