### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by rajeevramani** [pdfkit/pdfkit#82]
NoMethodError (undefined method `chomp' for nil:NilClass):

I am getting this error. 

I am using rails 3.0.3.

I completed all the setup including installation of wkhtmltopdf. I dont see any other error expect what I have listed here.

**Comment by paulkogel** [comment]
saved my day - even though `bundle exec ...` returned the proper path both on the command line and in the rails console!?

**Comment by cdwort** [comment]
@paulkogel Is this happening on a recent version of PDFKit? Mind posting your version?

**Comment by paulkogel** [comment]
I'm using `pdfkit (0.8.2)` and `wkhtmltopdf-binary (0.9.9.3)`

**Comment by gurunathsane** [comment]
yes 'which wkhtmltopdf' returned a path but I am still facing the same issue

**Comment by gurunathsane** [comment]
can we add custom path in config files instead direct change in Gems files

**Comment by sigmavirus24** [comment]
I'll post the link to the [configuration documentation](https://github.com/pdfkit/pdfkit#configuration) and lock this issue.
